import { CASE_DOCUMENTS_ROOT } from './constants';
import { buildInstructionStructure } from './instruction_structure_renderer';
import type { CaseArchiveScan, InstructionEntry } from './types';

function indentStructure(structure: string, indent = "  ") {
    if (structure.length === 0) {
        return "";
    }

    return structure
        .split('\n')
        .filter(line => line.length > 0)
        .map(line => `${indent}${line}`)
        .join('\n') + '\n';
}

/**
 * ZIP ルートに置く README を生成する。
 * AI が「事件資料」と「起案用指示書」を取り違えないよう、役割を明示している。
 */
export function buildArchiveReadme(dirName: string, structure: string, instructionEntries: InstructionEntry[], scan?: CaseArchiveScan) {
    const hasInstructions = instructionEntries.length > 0;
    const instructionsStructure = buildInstructionStructure(instructionEntries);
    const caseRoot = scan?.caseRoot || CASE_DOCUMENTS_ROOT;
    const directoryStructure = `📁 ${caseRoot}/\n${indentStructure(structure)}${instructionsStructure}`;
    const warningLine = scan && scan.warnings.length > 0
        ? `- **\`WARNINGS.md\`** — Notes about empty, very large, skipped, or otherwise risky files.\n`
        : '';

    let readmeContent = `# Project Archive for AI Analysis

This archive is prepared so an AI can understand the case materials before answering questions or drafting documents.

- **\`START_HERE.md\`** — Read this first. It explains how to use this archive safely.
- **\`CASE_INDEX.md\`** — Human-readable index of case files, suggested reading order, evidence numbers, dates, and warnings.
- **\`manifest.json\`** — Machine-readable index for tools and AI systems.
${warningLine}- **\`${caseRoot}/\`** — The user's actual case documents from the original folder \`${dirName}\` (briefs, evidence lists, transcripts, etc.).
  These are the files you should read, analyze, and use as source material.
`;

    if (hasInstructions) {
        readmeContent += `- **\`instructions/\`** — Bundled AI instructions and drafting references.
  Use these files as operational guidance for AI-assisted folder work and as reference material when drafting court documents.
`;
    }

    readmeContent += `
## Directory Structure

\`\`\`
${directoryStructure}\`\`\`
`;

    if (hasInstructions) {
        const instructionList = instructionEntries
            .map(entry => {
                const description = entry.isWorkflowGuide
                    ? 'Conversation flow for selecting a document type and collecting required facts.'
                    : entry.isTeamGuide
                        ? 'Codex virtual team roles and litigation-folder work instructions.'
                        : entry.isCommonRules
                            ? 'Common Markdown rules for all document types.'
                            : 'Reference instruction for the corresponding document type.';
                return `- \`${entry.displayPath}\` — ${description}`;
            })
            .join('\n');

        const hasCommonRules = instructionEntries.some(entry => entry.isCommonRules);
        const workflowGuide = instructionEntries.find(entry => entry.isWorkflowGuide);

        readmeContent += `
## AI Instructions

The files in \`instructions/\` are included as AI-facing operational guidance and drafting references.
Use the materials in \`${caseRoot}/\` for the facts of this case, and use the matching files in \`instructions/\` only as guidance.

${workflowGuide ? `When the user has not yet chosen a filing type, start with \`${workflowGuide.displayPath}\`.\n` : ''}${hasCommonRules ? 'Start with `instructions/sample.md`, then use the document-type instruction that best matches the filing you want to prepare.\n\n' : ''}Available instruction files:
${instructionList}
`;
    }

    readmeContent += `
---
Generated by Saiban System Archive Tool
`;

    return readmeContent;
}
