const fs = require('fs');
const path = require('path');
const ts = require('typescript');

const projectRoot = path.resolve(__dirname, '..');
const webDir = path.join(projectRoot, 'web');
const vendorDir = path.join(webDir, 'vendor');

const pdfEntryId = 'src/web/app';
const draftingEntryId = 'src/web/drafting';
const archiveEntryId = 'src/web/archive';
const moduleFiles = {
  'src/base/court_markdown': path.join(projectRoot, 'src/base/court_markdown.ts'),
  'src/lib/paged_toc': path.join(projectRoot, 'src/lib/paged_toc.ts'),
  'src/lib/ai_archive/case_index_renderer': path.join(projectRoot, 'src/lib/ai_archive/case_index_renderer.ts'),
  'src/lib/ai_archive/constants': path.join(projectRoot, 'src/lib/ai_archive/constants.ts'),
  'src/lib/ai_archive/inference': path.join(projectRoot, 'src/lib/ai_archive/inference.ts'),
  'src/lib/ai_archive/instruction_structure_renderer': path.join(projectRoot, 'src/lib/ai_archive/instruction_structure_renderer.ts'),
  'src/lib/ai_archive/manifest': path.join(projectRoot, 'src/lib/ai_archive/manifest.ts'),
  'src/lib/ai_archive/readme_renderer': path.join(projectRoot, 'src/lib/ai_archive/readme_renderer.ts'),
  'src/lib/ai_archive/renderers': path.join(projectRoot, 'src/lib/ai_archive/renderers.ts'),
  'src/lib/ai_archive/start_here_renderer': path.join(projectRoot, 'src/lib/ai_archive/start_here_renderer.ts'),
  'src/lib/ai_archive/utils': path.join(projectRoot, 'src/lib/ai_archive/utils.ts'),
  'src/lib/ai_archive/warnings_renderer': path.join(projectRoot, 'src/lib/ai_archive/warnings_renderer.ts'),
  [pdfEntryId]: path.join(projectRoot, 'src/web/app.ts'),
  [draftingEntryId]: path.join(projectRoot, 'src/web/drafting.ts'),
  'src/web/zip': path.join(projectRoot, 'src/web/zip.ts'),
  [archiveEntryId]: path.join(projectRoot, 'src/web/archive.ts')
};

const draftingTemplateOrder = [
  '訴状.md',
  '答弁書.md',
  '準備書面.md',
  '証拠説明書.md',
  '送付書.md',
  '期日請書.md',
  '事務連絡.md',
  '移送申立書.md',
  '控訴状.md',
  '控訴理由書.md',
  '上告状兼上告受理申立書.md',
  '上告理由書.md',
  '上告受理申立て理由書.md',
  '忌避申立書.md',
  '反訳書.md',
  '行政.住民監査請求書.md',
  '行政.審査請求書.md',
  '行政.反論書.md',
  '行政.開示請求.md',
  '行政.個人情報開示請求の取下書.md',
  '刑事.告訴状.md'
];

const draftingTemplateRank = new Map(draftingTemplateOrder.map((name, index) => [name, index]));

function normalizeModuleId(value) {
  return value.replace(/\\/g, '/').replace(/\.(ts|js)$/, '');
}

function compileTs(filePath) {
  const source = fs.readFileSync(filePath, 'utf-8');
  const result = ts.transpileModule(source, {
    compilerOptions: {
      target: ts.ScriptTarget.ES2021,
      module: ts.ModuleKind.CommonJS,
      esModuleInterop: true,
      noEmitOnError: false
    },
    fileName: filePath
  });
  return result.outputText;
}

function jsString(value) {
  return JSON.stringify(value);
}

fs.mkdirSync(webDir, { recursive: true });
fs.mkdirSync(vendorDir, { recursive: true });

function buildBundle(entryId, selectedModuleFiles) {
  const modulesSource = Object.entries(selectedModuleFiles)
    .map(([id, filePath]) => {
    const code = compileTs(filePath);
    return `${jsString(normalizeModuleId(id))}: function(require, module, exports) {\n${code}\n}`;
  })
  .join(',\n');

  return `// Generated by scripts/build_web.js. Do not edit directly.
(function () {
  var modules = {
${modulesSource}
  };
  var cache = {};
  function resolve(from, request) {
    if (request.charAt(0) !== '.') return request;
    var parts = from.split('/');
    parts.pop();
    var raw = parts.concat(request.split('/'));
    var out = [];
    for (var i = 0; i < raw.length; i++) {
      var part = raw[i];
      if (!part || part === '.') continue;
      if (part === '..') out.pop();
      else out.push(part);
    }
    return out.join('/').replace(/\\.(js|ts)$/, '');
  }
  function load(id) {
    if (cache[id]) return cache[id].exports;
    if (!modules[id]) throw new Error('Module not found: ' + id);
    var module = { exports: {} };
    cache[id] = module;
    modules[id](function (request) { return load(resolve(id, request)); }, module, module.exports);
    return module.exports;
  }
  load(${jsString(entryId)});
}());
`;
}

function readDraftingData() {
  const rulesPath = path.join(projectRoot, 'src/base/court_doc_rules.md');
  const templatesDir = path.join(projectRoot, 'src/templates');
  const templates = fs.readdirSync(templatesDir)
    .filter(name => name.endsWith('.md'))
    .sort((a, b) => {
      const rankA = draftingTemplateRank.has(a) ? draftingTemplateRank.get(a) : Number.MAX_SAFE_INTEGER;
      const rankB = draftingTemplateRank.has(b) ? draftingTemplateRank.get(b) : Number.MAX_SAFE_INTEGER;
      if (rankA !== rankB) return rankA - rankB;
      return a.localeCompare(b, 'ja');
    })
    .map(name => ({
      id: name,
      name: path.basename(name, '.md'),
      content: fs.readFileSync(path.join(templatesDir, name), 'utf-8')
    }));

  return {
    generatedAt: new Date().toISOString(),
    rules: fs.readFileSync(rulesPath, 'utf-8'),
    templates
  };
}

function readInstructionSources() {
  const baseDir = path.join(projectRoot, 'src/base');
  const templatesDir = path.join(projectRoot, 'src/templates');
  const instructionPath = path.join(baseDir, 'court_doc_rules.md');
  const instructionContent = fs.readFileSync(instructionPath, 'utf-8');
  const placeholder = /```markdown\r?\n```/;
  const files = [];

  const samplePath = path.join(baseDir, 'sample.md');
  if (fs.existsSync(samplePath)) {
    files.push({ path: samplePath, name: 'sample.md' });
  }

  const templateFiles = fs.readdirSync(templatesDir)
    .filter(name => name.endsWith('.md'))
    .sort((a, b) => {
      const rankA = draftingTemplateRank.has(a) ? draftingTemplateRank.get(a) : Number.MAX_SAFE_INTEGER;
      const rankB = draftingTemplateRank.has(b) ? draftingTemplateRank.get(b) : Number.MAX_SAFE_INTEGER;
      if (rankA !== rankB) return rankA - rankB;
      return a.localeCompare(b, 'ja');
    })
    .map(name => ({ path: path.join(templatesDir, name), name }));

  files.push(...templateFiles);

  return { instructionContent, placeholder, files };
}

function buildArchiveStartHere(files) {
  const documentTypes = files
    .filter(file => file.name !== 'sample.md')
    .map(file => path.basename(file.name, '.md'))
    .map(name => `- ${name}`)
    .join('\n');

  return `# START_HERE - Chat AIへの指示

あなたは「法匪（HOUHI）」の書面起案アシスタントです。
このZIPには、日本の裁判実務向けMarkdown書面を作るための共通ルールと書面別テンプレートが入っています。

ユーザーが具体的な要望を送っている場合は、その要望を優先してください。
必要な資料や情報が不足している場合は、推測で完成させず、具体的に質問してください。

最終的に書面を作るときは、法匪のMarkdown仕様に従ってMarkdown本文を生成し、法匪Webの「PDF変換 / 印刷」に貼り付けてプレビューするよう案内してください。

## 利用できる書面テンプレート

${documentTypes}
`;
}

function readArchiveData() {
  const { instructionContent, placeholder, files } = readInstructionSources();
  const instructions = [
    {
      displayPath: 'instructions/00_START_HERE.md',
      content: buildArchiveStartHere(files),
      isCommonRules: false,
      isWorkflowGuide: true
    }
  ];

  for (const file of files) {
    const content = fs.readFileSync(file.path, 'utf-8');
    const replacement = `\`\`\`markdown\n${content.trim()}\n\`\`\``;
    instructions.push({
      displayPath: `instructions/${file.name}`,
      content: instructionContent.replace(placeholder, replacement),
      isCommonRules: file.name === 'sample.md',
      isWorkflowGuide: false
    });
  }

  return {
    generatedAt: new Date().toISOString(),
    instructions
  };
}

fs.writeFileSync(path.join(webDir, 'app.js'), buildBundle(pdfEntryId, {
  'src/base/court_markdown': moduleFiles['src/base/court_markdown'],
  'src/lib/paged_toc': moduleFiles['src/lib/paged_toc'],
  [pdfEntryId]: moduleFiles[pdfEntryId]
}), 'utf-8');
fs.writeFileSync(path.join(webDir, 'drafting.js'), buildBundle(draftingEntryId, {
  [draftingEntryId]: moduleFiles[draftingEntryId]
}), 'utf-8');
fs.writeFileSync(path.join(webDir, 'archive.js'), buildBundle(archiveEntryId, {
  'src/lib/ai_archive/case_index_renderer': moduleFiles['src/lib/ai_archive/case_index_renderer'],
  'src/lib/ai_archive/constants': moduleFiles['src/lib/ai_archive/constants'],
  'src/lib/ai_archive/inference': moduleFiles['src/lib/ai_archive/inference'],
  'src/lib/ai_archive/instruction_structure_renderer': moduleFiles['src/lib/ai_archive/instruction_structure_renderer'],
  'src/lib/ai_archive/manifest': moduleFiles['src/lib/ai_archive/manifest'],
  'src/lib/ai_archive/readme_renderer': moduleFiles['src/lib/ai_archive/readme_renderer'],
  'src/lib/ai_archive/renderers': moduleFiles['src/lib/ai_archive/renderers'],
  'src/lib/ai_archive/start_here_renderer': moduleFiles['src/lib/ai_archive/start_here_renderer'],
  'src/lib/ai_archive/utils': moduleFiles['src/lib/ai_archive/utils'],
  'src/lib/ai_archive/warnings_renderer': moduleFiles['src/lib/ai_archive/warnings_renderer'],
  'src/web/zip': moduleFiles['src/web/zip'],
  [archiveEntryId]: moduleFiles[archiveEntryId]
}), 'utf-8');
fs.writeFileSync(
  path.join(webDir, 'drafting-data.js'),
  `window.HOUHI_DRAFTING_DATA = ${JSON.stringify(readDraftingData())};\n`,
  'utf-8'
);
fs.writeFileSync(
  path.join(webDir, 'archive-data.js'),
  `window.HOUHI_ARCHIVE_DATA = ${JSON.stringify(readArchiveData())};\n`,
  'utf-8'
);
fs.copyFileSync(path.join(projectRoot, 'src/base/style.css'), path.join(webDir, 'court.css'));
fs.copyFileSync(
  path.join(projectRoot, 'node_modules/pagedjs/dist/paged.polyfill.min.js'),
  path.join(vendorDir, 'paged.polyfill.min.js')
);

console.log('[web] built web/app.js');
console.log('[web] built web/drafting.js');
console.log('[web] built web/drafting-data.js');
console.log('[web] built web/archive.js');
console.log('[web] built web/archive-data.js');
console.log('[web] copied web/court.css');
console.log('[web] copied web/vendor/paged.polyfill.min.js');
