// Generated by scripts/build_web.js. Do not edit directly.
(function () {
  var modules = {
"src/base/court_markdown": function(require, module, exports) {
"use strict";
/**
 * 裁判文書用 Markdown -> HTML 変換スクリプト
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.convertMarkdownToCourtHtml = convertMarkdownToCourtHtml;
/**
 * 文字列の視覚的な幅（em単位）を計算します。
 * 半角文字を0.5em、全角文字を1emとして計算します。
 */
function getVisualWidth(text) {
    let width = 0;
    for (let i = 0; i < text.length; i++) {
        const code = text.charCodeAt(i);
        // 半角文字（ASCII, 半角カナ）は0.5、それ以外は1
        if ((code >= 0x0020 && code <= 0x007e) || (code >= 0xff61 && code <= 0xff9f)) {
            width += 0.5;
        }
        else {
            width += 1.0;
        }
    }
    return width;
}
function escapeHtmlAttribute(value) {
    return String(value)
        .replace(/&/g, '&amp;')
        .replace(/"/g, '&quot;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
}
function escapeHtml(value) {
    return String(value)
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
}
function stripInlineMarkdown(value) {
    return String(value)
        .replace(/\\\+\+/g, '++')
        .replace(/\+\+(.+?)\+\+/g, '$1');
}
function renderInlineMarkdown(value) {
    const escapedPlus = '\uE000';
    return escapeHtml(value)
        .replace(/\\\+\+/g, escapedPlus)
        .replace(/\+\+(.+?)\+\+/g, (_match, text) => `<span class="underline">${text}</span>`)
        .replace(new RegExp(escapedPlus, 'g'), '++');
}
/**
 * Markdownテキストを裁判文書用のHTMLに変換します。
 */
function convertMarkdownToCourtHtml(markdown) {
    const lines = markdown.split(/\r?\n/);
    let html = '';
    let lastLevel = 0;
    let inTable = false;
    let tableBuffer = [];
    let tableClass = '';
    let tableHasHeader = false;
    let inRightBlock = false;
    let inLeftBlock = false;
    let lastHeader = '';
    let inEvidenceTable = false;
    let evidenceTableBuffer = [];
    let inSimpleList = false;
    // インデント用のヘルパー
    const indent = (level) => '    '.repeat(level);
    const nl = '\n';
    const tocElement = '<cssj:make-toc xmlns:cssj="http://www.cssj.jp/ns/cssjml" counter="page" type="decimal"></cssj:make-toc>';
    const headingTag = (level) => `h${Math.min(Math.max(level, 1), 6)}`;
    // --- 事前スキャン: 各エリアのグローバルな列幅を計算 ---
    const rightColWidths = [];
    const leftColWidths = [];
    const attColWidths = [];
    const defaultColWidths = [];
    let scanHeader = '';
    let inScanEvidenceTable = false;
    let isSoufusho = false;
    let scanInRight = false;
    let scanInLeft = false;
    for (let line of lines) {
        const trimmed = line.trim();
        // ブロック検出
        if (trimmed === '### --右') {
            scanInRight = true;
            scanInLeft = false;
            continue;
        }
        if (trimmed === '### --左') {
            scanInLeft = true;
            scanInRight = false;
            continue;
        }
        if (trimmed === '### --') {
            scanInRight = false;
            scanInLeft = false;
            continue;
        }
        if (trimmed.startsWith('#')) {
            // 改ページマーカー等はヘッダーとして扱わない
            if (/^### --.*--$/.test(trimmed) || trimmed === '### ---' || trimmed === '### -')
                continue;
            scanHeader = trimmed.replace(/^#*\s*/, '').trim();
            if (scanHeader === '送付書') {
                isSoufusho = true;
            }
        }
        const tableMatch = trimmed.match(/^\|(.*)\|$/);
        const listTableMatch = trimmed.match(/^[-*] (.*?)[：:](.*)$/);
        const numberedListTableMatch = trimmed.match(/^([0-9０-９]+)[　\s]+(.+?)[：:](.*)$/);
        if (tableMatch || listTableMatch || numberedListTableMatch) {
            // 証拠説明書テーブルの開始を検出
            // 「号証」を含むヘッダー行を証拠説明書テーブルとして扱う
            if (tableMatch && (tableMatch[1].includes('号証'))) {
                inScanEvidenceTable = true;
            }
            // 証拠説明書テーブルは除外（別扱い）
            if (!inScanEvidenceTable) {
                // セパレーター行（|:---|:---|...）は除外
                if (tableMatch && /^[\s|:-]+$/.test(tableMatch[1])) {
                    continue;
                }
                let cells;
                if (tableMatch) {
                    cells = tableMatch[1].split('|');
                }
                else if (numberedListTableMatch) {
                    cells = [numberedListTableMatch[2], numberedListTableMatch[3]];
                }
                else {
                    cells = [listTableMatch[1], listTableMatch[2]];
                }
                // どの幅配列を使うか決定
                let targetWidths = defaultColWidths;
                if (numberedListTableMatch || scanHeader === '附属書類' || scanHeader === '証拠書類') {
                    targetWidths = attColWidths;
                }
                else if (scanInRight) {
                    targetWidths = rightColWidths;
                }
                else if (scanInLeft) {
                    targetWidths = leftColWidths;
                }
                cells.forEach((cell, i) => {
                    const w = getVisualWidth(stripInlineMarkdown(cell.trim()));
                    if (!targetWidths[i] || w > targetWidths[i])
                        targetWidths[i] = w;
                });
            }
        }
        else if (inScanEvidenceTable) {
            // テーブル行以外が来たら証拠説明書テーブル終了
            inScanEvidenceTable = false;
        }
    }
    // テーブルをフラッシュしてHTMLを生成する内部関数
    const flushTable = () => {
        if (tableBuffer.length === 0)
            return '';
        let tableHtml = '';
        const effectiveClass = tableHasHeader ? tableClass + ' has-header' : tableClass;
        tableHtml += indent(lastLevel) + `<table class="${effectiveClass}">` + nl;
        const renderRow = (row, tag) => {
            let rowHtml = indent(lastLevel + 2) + '<tr>' + nl;
            row.forEach((cell, i) => {
                const text = cell.trim();
                const displayText = stripInlineMarkdown(text);
                const isAmount = tag === 'td' && i > 0 && /^[0-9０-９,，．.]+円?$/.test(displayText);
                const classes = [];
                if (tableClass.includes('info') || tableClass.includes('att'))
                    classes.push(`col-${i + 1}`);
                if (isAmount)
                    classes.push('val');
                const classAttr = classes.length > 0 ? ` class="${classes.join(' ')}"` : '';
                rowHtml += indent(lastLevel + 3) + `<${tag}${classAttr}>${renderInlineMarkdown(text)}</${tag}>` + nl;
            });
            rowHtml += indent(lastLevel + 2) + '</tr>' + nl;
            return rowHtml;
        };
        if (tableHasHeader && tableBuffer.length > 0) {
            tableHtml += indent(lastLevel + 1) + '<thead>' + nl;
            tableHtml += renderRow(tableBuffer[0], 'th');
            tableHtml += indent(lastLevel + 1) + '</thead>' + nl;
            tableHtml += indent(lastLevel + 1) + '<tbody>' + nl;
            tableBuffer.slice(1).forEach(row => { tableHtml += renderRow(row, 'td'); });
            tableHtml += indent(lastLevel + 1) + '</tbody>' + nl;
        }
        else {
            tableBuffer.forEach(row => { tableHtml += renderRow(row, 'td'); });
        }
        tableHtml += indent(lastLevel) + '</table>' + nl;
        tableBuffer = [];
        tableHasHeader = false;
        return tableHtml;
    };
    // 証拠説明書テーブルをフラッシュしてHTMLを生成する内部関数
    const flushEvidenceTable = () => {
        if (evidenceTableBuffer.length === 0)
            return '';
        let tableHtml = '';
        // ヘッダー行とセパレーター行をスキップ
        const headerRow = evidenceTableBuffer[0];
        const dataRows = evidenceTableBuffer.slice(1); // セパレーターは既に除外済みのためヘッダーのみスキップ
        tableHtml += indent(lastLevel) + '<table class="evidence">' + nl;
        // ヘッダー行を生成
        tableHtml += indent(lastLevel + 1) + '<thead>' + nl;
        tableHtml += indent(lastLevel + 2) + '<tr>' + nl;
        headerRow.forEach((cell, i) => {
            const text = cell.trim();
            tableHtml += indent(lastLevel + 3) + `<th class="col-${i + 1}">${renderInlineMarkdown(text)}</th>` + nl;
        });
        tableHtml += indent(lastLevel + 2) + '</tr>' + nl;
        tableHtml += indent(lastLevel + 1) + '</thead>' + nl;
        // データ行を生成
        tableHtml += indent(lastLevel + 1) + '<tbody>' + nl;
        // 各列で結合が必要な行を追跡
        const rowspanMap = new Map(); // key: colIndex, value: { rowIndex, span, text }
        dataRows.forEach((row, rowIndex) => {
            tableHtml += indent(lastLevel + 2) + '<tr>' + nl;
            row.forEach((cell, colIndex) => {
                const text = cell.trim();
                // この列が既に結合中かチェック
                if (rowspanMap.has(colIndex)) {
                    const info = rowspanMap.get(colIndex);
                    if (rowIndex < info.rowIndex + info.span) {
                        // まだ結合中なのでセルをスキップ
                        return;
                    }
                }
                // 空のセルの場合、上のセルと結合
                if (text === '') {
                    // 上方向に遡って最初の非空セルを探す
                    let spanCount = 1;
                    let lookupRow = rowIndex - 1;
                    let mergedText = '';
                    while (lookupRow >= 0) {
                        const prevText = dataRows[lookupRow][colIndex].trim();
                        if (prevText !== '') {
                            mergedText = prevText;
                            // 既存のrowspanを更新
                            if (rowspanMap.has(colIndex)) {
                                const existingInfo = rowspanMap.get(colIndex);
                                if (lookupRow >= existingInfo.rowIndex && lookupRow < existingInfo.rowIndex + existingInfo.span) {
                                    // 既存の結合を拡張
                                    existingInfo.span++;
                                    return;
                                }
                            }
                            // 新しいrowspanの開始位置まで遡る
                            let startRow = lookupRow;
                            while (startRow > 0 && dataRows[startRow - 1][colIndex].trim() === '') {
                                startRow--;
                                spanCount++;
                            }
                            // この空セルまでのスパンをカウント
                            spanCount = rowIndex - startRow + 1;
                            // 既存のマッピングを更新
                            if (rowspanMap.has(colIndex)) {
                                const info = rowspanMap.get(colIndex);
                                if (info.rowIndex === startRow) {
                                    info.span = spanCount + 1;
                                }
                            }
                            break;
                        }
                        lookupRow--;
                        spanCount++;
                    }
                    return; // 空のセルは出力しない
                }
                // 下方向に空のセルがいくつ続くかカウント
                let rowspan = 1;
                for (let nextRow = rowIndex + 1; nextRow < dataRows.length; nextRow++) {
                    if (dataRows[nextRow][colIndex].trim() === '') {
                        rowspan++;
                    }
                    else {
                        break;
                    }
                }
                if (rowspan > 1) {
                    rowspanMap.set(colIndex, { rowIndex, span: rowspan, text });
                }
                const rowspanAttr = rowspan > 1 ? ` rowspan="${rowspan}"` : '';
                tableHtml += indent(lastLevel + 3) + `<td class="col-${colIndex + 1}"${rowspanAttr}>${renderInlineMarkdown(text)}</td>` + nl;
            });
            tableHtml += indent(lastLevel + 2) + '</tr>' + nl;
        });
        tableHtml += indent(lastLevel + 1) + '</tbody>' + nl;
        tableHtml += indent(lastLevel) + '</table>' + nl;
        evidenceTableBuffer = [];
        return tableHtml;
    };
    const markers = [
        { level: 1, regex: /^#*\s*(第[0-9]+)[　\s]/ },
        { level: 2, regex: /^#*\s*([0-9]+)[　\s]/ },
        { level: 3, regex: /^#*\s*(\([0-9]+\))[　\s]/ },
        { level: 4, regex: /^#*\s*([ア-ン])[　\s]/ },
        { level: 5, regex: /^#*\s*(\([ア-ン]\))[　\s]/ },
        { level: 6, regex: /^#*\s*([a-z])[　\s]/ },
        { level: 7, regex: /^#*\s*(\([a-z]\))[　\s]/ }
    ];
    function getLevelInfo(line) {
        for (const m of markers) {
            const match = line.match(m.regex);
            if (match) {
                return { level: m.level, marker: match[1] };
            }
        }
        return null;
    }
    for (let line of lines) {
        const trimmedLine = line.trim();
        if (!trimmedLine)
            continue;
        // 右寄せ・左寄せブロックの開始・終了
        if (trimmedLine === '### --右') {
            if (inTable) {
                html += flushTable();
                inTable = false;
            }
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += '<div class="right">' + nl;
            inRightBlock = true;
            continue;
        }
        if (trimmedLine === '### --左') {
            if (inTable) {
                html += flushTable();
                inTable = false;
            }
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += '<div class="left">' + nl;
            inLeftBlock = true;
            continue;
        }
        if (trimmedLine === '### --') {
            if (inRightBlock || inLeftBlock) {
                if (inTable) {
                    html += flushTable();
                    inTable = false;
                }
                while (lastLevel > 0) {
                    html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                    lastLevel--;
                }
                html += '</div>' + nl;
                inRightBlock = false;
                inLeftBlock = false;
                continue;
            }
        }
        // テーブル行の処理: |書類名|通数|、- 書類名：通数、1 書類名：通数
        const tableMatch = trimmedLine.match(/^\|(.*)\|$/);
        const listTableMatch = trimmedLine.match(/^[-*] (.*?)[：:](.*)$/);
        const numberedListTableMatch = trimmedLine.match(/^([0-9０-９]+)[　\s]+(.+?)[：:](.*)$/);
        if (tableMatch || listTableMatch || numberedListTableMatch) {
            // セパレーター行（|:---|:---|...）をチェック
            const isSeparator = tableMatch && /^[\s|:-]+$/.test(tableMatch[1]);
            if (isSeparator) {
                tableHasHeader = true;
                continue;
            }
            // ヘッダー行（「号証」を含む）をチェック
            const isEvidenceHeader = tableMatch && tableMatch[1].includes('号証');
            if (isEvidenceHeader || (inEvidenceTable && tableMatch)) {
                // 証拠説明書テーブル
                if (!inEvidenceTable) {
                    while (lastLevel > 0) {
                        html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                        lastLevel--;
                    }
                    inEvidenceTable = true;
                }
                if (tableMatch) {
                    const cells = tableMatch[1].split('|');
                    evidenceTableBuffer.push(cells);
                }
                continue;
            }
            else if (!inTable) {
                // 通常のテーブル（info/att）
                while (lastLevel > 0) {
                    html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                    lastLevel--;
                }
                tableHasHeader = false;
                if (numberedListTableMatch || lastHeader === '附属書類' || lastHeader === '証拠書類') {
                    tableClass = 'att';
                }
                else if (inRightBlock) {
                    tableClass = 'info right-info';
                }
                else if (inLeftBlock) {
                    tableClass = 'info left-info';
                }
                else {
                    tableClass = 'info default-info';
                }
                inTable = true;
            }
            let cells;
            if (tableMatch) {
                cells = tableMatch[1].split('|');
            }
            else if (numberedListTableMatch) {
                cells = [numberedListTableMatch[2], numberedListTableMatch[3]];
            }
            else {
                cells = [listTableMatch[1], listTableMatch[2]];
            }
            tableBuffer.push(cells);
            continue;
        }
        else if (inTable) {
            html += flushTable();
            inTable = false;
        }
        else if (inEvidenceTable) {
            html += flushEvidenceTable();
            inEvidenceTable = false;
        }
        // シンプルなリスト形式の処理: * 項目名
        const simpleListMatch = trimmedLine.match(/^[*＊]\s+(.+)$/);
        if (simpleListMatch) {
            if (!inSimpleList) {
                while (lastLevel > 0) {
                    html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                    lastLevel--;
                }
                html += '<ul>' + nl;
                inSimpleList = true;
            }
            html += indent(1) + `<li>${renderInlineMarkdown(simpleListMatch[1])}</li>` + nl;
            continue;
        }
        else if (inSimpleList) {
            html += '</ul>' + nl;
            inSimpleList = false;
        }
        // 画像の処理: ![説明](画像パス)
        // 書面では常に中央寄せの独立ブロックとして配置する
        const imageMatch = trimmedLine.match(/^!\[([^\]]*)\]\(([^)]+)\)$/);
        if (imageMatch) {
            if (inRightBlock || inLeftBlock) {
                while (lastLevel > 0) {
                    html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                    lastLevel--;
                }
                html += '</div>' + nl;
                inRightBlock = false;
                inLeftBlock = false;
            }
            const alt = escapeHtmlAttribute(imageMatch[1].trim());
            const src = escapeHtmlAttribute(imageMatch[2].trim());
            const currentIndent = indent(lastLevel + (lastLevel > 0 ? 1 : 0));
            html += currentIndent + `<div class="image-block"><img src="${src}" alt="${alt}" /></div>` + nl;
            continue;
        }
        // 空行（スペーサー）マーカーの処理: ### -
        // 空行は入力上は捨てられるため、見た目の空行を挿入する
        if (trimmedLine === '### -') {
            const currentIndent = indent(lastLevel + (lastLevel > 0 ? 1 : 0));
            html += currentIndent + '<div class="blank-line"></div>' + nl;
            continue;
        }
        // 目次マーカーの処理: ### --目次
        // Copper PDF の cssj:make-toc により、文書内の h1-h6 から目次を生成する
        if (trimmedLine === '### --目次') {
            if (inRightBlock || inLeftBlock) {
                while (lastLevel > 0) {
                    html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                    lastLevel--;
                }
                html += '</div>' + nl;
                inRightBlock = false;
                inLeftBlock = false;
            }
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += '<div class="toc-title">目次</div>' + nl;
            html += tocElement + nl;
            continue;
        }
        // 区切り線マーカーの処理: ### ---
        // 改ページはせず、点線（区切り線）を挿入する
        if (trimmedLine === '### ---') {
            // 右/左ブロック内で使われた場合も安全に閉じる
            if (inRightBlock || inLeftBlock) {
                while (lastLevel > 0) {
                    html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                    lastLevel--;
                }
                html += '</div>' + nl;
                inRightBlock = false;
                inLeftBlock = false;
            }
            // リストを閉じて区切り線を挿入
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += '<hr class="separator" />' + nl;
            continue;
        }
        // 改ページマーカーの処理: ### -- 任意のテキスト --
        if (/^### --.*--$/.test(trimmedLine)) {
            // テキスト部分を抽出
            const match = trimmedLine.match(/^### --\s*(.*?)\s*--$/);
            const breakText = match ? match[1].trim() : '';
            // リストを閉じて改ページを挿入
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += `<div class="break">(${renderInlineMarkdown(breakText)})</div>` + nl;
            continue;
        }
        const levelInfo = getLevelInfo(trimmedLine);
        const isHeader = trimmedLine.startsWith('#');
        const markerText = levelInfo
            ? trimmedLine.replace(/^#*\s*/, '').replace(levelInfo.marker, '').trim()
            : '';
        const isTocHeading = !!levelInfo && (isHeader || (levelInfo.level <= 2 && !markerText.includes('。') && !/[：:]/.test(markerText)));
        const liClass = isTocHeading ? ' class="heading-item"' : '';
        let level, text;
        if (levelInfo) {
            level = levelInfo.level;
            // マーカーと#を除去
            text = markerText;
        }
        else {
            // マーカーがない場合は現在のレベルの継続（最初からマーカーがない場合はレベル0）
            level = lastLevel;
            text = trimmedLine.replace(/^#+\s*/, '').trim();
        }
        // 階層の調整
        let openedNewLevel = false;
        while (lastLevel < level) {
            if (lastLevel === 0) {
                lastLevel = level;
            }
            else {
                lastLevel++;
            }
            const currentLiClass = lastLevel === level ? liClass : '';
            html += indent(lastLevel - 1) + `<ol class="lvl${lastLevel}">` + nl + indent(lastLevel) + `<li${currentLiClass}>` + nl;
            openedNewLevel = true;
        }
        while (lastLevel > level) {
            html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
            lastLevel--;
        }
        if (lastLevel === level && levelInfo && !openedNewLevel) {
            // 新しいマーカーがある場合は次の li へ
            html += indent(lastLevel) + '</li>' + nl + indent(lastLevel) + `<li${liClass}>` + nl;
        }
        const currentIndent = indent(lastLevel + (lastLevel > 0 ? 1 : 0));
        if (isTocHeading) {
            lastHeader = text; // ヘッダテキストを保存
            if (levelInfo) {
                const tagName = headingTag(levelInfo.level);
                html += currentIndent + `<${tagName}>${levelInfo.marker}　${renderInlineMarkdown(text)}</${tagName}>` + nl;
            }
        }
        else if (isHeader) {
            lastHeader = text; // ヘッダテキストを保存
            // マーカーがないヘッダはリストの外に出し、文書タイトルとして扱う
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += `<div class="doc-title">${renderInlineMarkdown(text)}</div>` + nl;
            lastLevel = 0;
            continue;
        }
        else if (text === '以上') {
            // 「以上」のみの行は特別扱い（リストを閉じて右寄せ）
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += `<div class="end-mark">${renderInlineMarkdown(text)}</div>` + nl;
            lastLevel = 0;
            continue;
        }
        else if (text === '記') {
            // 「記」のみの行は特別扱い（リストを閉じてセンタリング）
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += `<div class="center-mark">${renderInlineMarkdown(text)}</div>` + nl;
            lastLevel = 0;
            continue;
        }
        else if (/^(?:(?:令和|平成|昭和|大正|明治)\s*(?:[0-9０-９]{1,2}|[元〇○一二三四五六七八九十]{1,3})|[0-9０-９]{1,4})\s*年\s*(?:[0-9０-９]{1,2}|[〇○一二三四五六七八九十]{1,3})\s*月\s*(?:[0-9０-９]{1,2}|[元〇○一二三四五六七八九十]{1,3})\s*日$/.test(text)) {
            // 日付の識別 (和暦・西暦、数字・漢数字、元年などに対応)
            html += currentIndent + `<div class="date">${renderInlineMarkdown(text)}</div>` + nl;
        }
        else if (/.*[　\s](?:御中|様)$/.test(text)) {
            // 宛先の識別
            html += currentIndent + `<div class="dest">${renderInlineMarkdown(text)}</div>` + nl;
        }
        else {
            html += currentIndent + `<p>${renderInlineMarkdown(text)}</p>` + nl;
        }
        lastLevel = level;
    }
    // 残ったタグを閉じる
    if (inTable) {
        html += flushTable();
    }
    if (inEvidenceTable) {
        html += flushEvidenceTable();
    }
    if (inSimpleList) {
        html += '</ul>' + nl;
    }
    while (lastLevel > 0) {
        html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
        lastLevel--;
    }
    // スタイルを生成
    let styleTag = '';
    if (rightColWidths.length > 0 || leftColWidths.length > 0 || attColWidths.length > 0 || defaultColWidths.length > 0 || isSoufusho) {
        styleTag = '<style>' + nl;
        if (isSoufusho) {
            styleTag += '* { font-size: 10.5pt; }' + nl;
        }
        const generateTableStyle = (widths, className) => {
            let css = '';
            widths.forEach((w, i) => {
                if (w) {
                    w += 1; // 余裕を持たせる
                    // 附属書類・証拠書類（attクラス）の1列目はカウンター（2em）があるため幅を広げる
                    if (className === 'att' && i === 0) {
                        w += 2.5;
                    }
                    css += `table.${className} td.col-${i + 1} { width: ${w}em; }` + nl;
                }
            });
            return css;
        };
        styleTag += generateTableStyle(rightColWidths, 'right-info');
        styleTag += generateTableStyle(leftColWidths, 'left-info');
        styleTag += generateTableStyle(attColWidths, 'att');
        styleTag += generateTableStyle(defaultColWidths, 'default-info'); // クラス指定がない通常のinfoテーブル用
        styleTag += '</style>' + nl;
    }
    return styleTag + html;
}
/**
 * ページ内のすべての <pre> タグを裁判文書形式に変換します。
 */
async function renderMarkdown() {
    const preElements = document.querySelectorAll('pre');
    for (const pre of Array.from(preElements)) {
        let markdown = pre.textContent;
        const src = pre.getAttribute('data-src');
        if (src) {
            try {
                const response = await fetch(src);
                if (response.ok) {
                    markdown = await response.text();
                }
                else {
                    console.error(`Failed to load markdown from ${src}: ${response.status}`);
                }
            }
            catch (e) {
                console.error(`Error fetching markdown from ${src}:`, e);
            }
        }
        if (!markdown.trim())
            continue;
        const html = convertMarkdownToCourtHtml(markdown);
        // pre要素を変換後のHTMLで置き換える
        const container = document.createElement('div');
        container.className = (pre.className ? pre.className + ' ' : '') + 'content-container';
        container.innerHTML = html;
        pre.parentNode.replaceChild(container, pre);
    }
}
// Node.js環境用のエクスポート
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { convertMarkdownToCourtHtml };
}
else {
    window.convertMarkdownToCourtHtml = convertMarkdownToCourtHtml;
    // ブラウザ環境では自動実行
    window.__houhiMarkdownReady = false;
    window.__houhiMarkdownPromise = null;
    document.addEventListener('DOMContentLoaded', () => {
        const promise = renderMarkdown();
        window.__houhiMarkdownPromise = promise;
        promise.finally(() => {
            window.__houhiMarkdownReady = true;
        });
    });
}

},
"src/lib/paged_toc": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.prepareChromeToc = prepareChromeToc;
exports.fillChromeTocPageNumbers = fillChromeTocPageNumbers;
exports.applyManualPageNumbers = applyManualPageNumbers;
exports.getPagedTocBrowserScript = getPagedTocBrowserScript;
function prepareChromeToc(root = document) {
    const tocRoots = Array.prototype.slice.call(root.querySelectorAll('[data-houhi-chrome-toc]'));
    if (tocRoots.length === 0)
        return;
    const headings = Array.prototype.slice.call(root.querySelectorAll('h1, h2'));
    const targetHeadings = headings.filter(heading => !heading.closest('[data-houhi-chrome-toc]'));
    targetHeadings.forEach((heading, index) => {
        if (!heading.getAttribute('data-houhi-toc-id')) {
            heading.setAttribute('data-houhi-toc-id', `houhi-toc-${index + 1}`);
        }
    });
    tocRoots.forEach(tocRoot => {
        tocRoot.innerHTML = '';
        tocRoot.setAttribute('data-houhi-chrome-toc', 'ready');
        let currentLevel1Item = null;
        targetHeadings.forEach(heading => {
            const isLevel2 = heading.tagName.toLowerCase() === 'h2';
            const li = root.createElement('li');
            li.setAttribute('data-houhi-toc-target', heading.getAttribute('data-houhi-toc-id') || '');
            const link = root.createElement('a');
            const title = root.createElement('span');
            title.className = 'cssj-title';
            title.textContent = (heading.textContent || '').trim();
            const page = root.createElement('span');
            page.className = 'cssj-page';
            page.textContent = ' ';
            const leader = root.createElement('span');
            leader.className = 'cssj-leader';
            link.appendChild(title);
            link.appendChild(leader);
            link.appendChild(page);
            li.appendChild(link);
            if (isLevel2 && currentLevel1Item) {
                let nested = currentLevel1Item.querySelector(':scope > ul');
                if (!nested) {
                    nested = root.createElement('ul');
                    currentLevel1Item.appendChild(nested);
                }
                nested.appendChild(li);
            }
            else {
                tocRoot.appendChild(li);
                currentLevel1Item = isLevel2 ? null : li;
            }
        });
    });
}
function cssEscape(value) {
    const cssApi = globalThis.CSS;
    if (cssApi && typeof cssApi.escape === 'function') {
        return cssApi.escape(value);
    }
    return value.replace(/["\\]/g, '\\$&');
}
function findPagedCloneForSource(root, source) {
    const ref = source && source.getAttribute('data-ref');
    if (ref) {
        const clone = root.querySelector(`.pagedjs_pages [data-ref="${cssEscape(ref)}"]`);
        if (clone)
            return clone;
    }
    const tocId = source && source.getAttribute('data-houhi-toc-id');
    if (tocId) {
        return root.querySelector(`.pagedjs_pages [data-houhi-toc-id="${cssEscape(tocId)}"]`);
    }
    return null;
}
function getPageNumberForElement(element) {
    const page = element && element.closest('.pagedjs_page');
    if (!page)
        return '';
    return page.getAttribute('data-page-number') || page.dataset.pageNumber || '';
}
function fillChromeTocPageNumbers(root = document) {
    const sourceById = {};
    Array.prototype.forEach.call(root.querySelectorAll('h1[data-houhi-toc-id], h2[data-houhi-toc-id]'), (heading) => {
        sourceById[heading.getAttribute('data-houhi-toc-id') || ''] = heading;
    });
    Array.prototype.forEach.call(root.querySelectorAll('.pagedjs_pages [data-houhi-chrome-toc] li[data-houhi-toc-target]'), (item) => {
        const targetId = item.getAttribute('data-houhi-toc-target') || '';
        const source = sourceById[targetId];
        const clone = findPagedCloneForSource(root, source);
        const pageNumber = getPageNumberForElement(clone);
        const pageSpan = item.querySelector('.cssj-page');
        if (pageSpan && pageNumber) {
            pageSpan.textContent = pageNumber;
        }
    });
}
function applyManualPageNumbers(root = document) {
    const pageNumberStyle = root.createElement('style');
    pageNumberStyle.setAttribute('data-houhi-pagedjs-page-numbers', 'manual');
    pageNumberStyle.textContent = 'html[data-houhi-pdf-engine="chrome"] body::before { content: none !important; display: none !important; } @page { @bottom-center { content: none; } } .pagedjs_pages .pagedjs_margin-bottom .pagedjs_margin-bottom-center .pagedjs_margin-content::after { content: none !important; }';
    root.head.appendChild(pageNumberStyle);
    Array.prototype.forEach.call(root.querySelectorAll('.pagedjs_page'), (page, index) => {
        const footer = page.querySelector('.pagedjs_margin-bottom-center .pagedjs_margin-content');
        if (footer) {
            if (footer.parentElement) {
                footer.parentElement.classList.add('hasContent');
            }
            footer.textContent = `- ${index + 1} -`;
        }
    });
}
function getPagedTocBrowserScript() {
    return `
var cssEscape = ${cssEscape.toString()};
var findPagedCloneForSource = ${findPagedCloneForSource.toString()};
var getPageNumberForElement = ${getPageNumberForElement.toString()};
function prepareChromeToc(){(${prepareChromeToc.toString()})(document);}
function fillChromeTocPageNumbers(){(${fillChromeTocPageNumbers.toString()})(document);}
function applyManualPageNumbers(){(${applyManualPageNumbers.toString()})(document);}
`.trim();
}

},
"src/web/document_title": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.extractMarkdownDocumentTitle = extractMarkdownDocumentTitle;
exports.sanitizeDownloadTitle = sanitizeDownloadTitle;
exports.buildPdfDocumentTitle = buildPdfDocumentTitle;
const DEFAULT_PDF_DOCUMENT_TITLE = '法匪 PDF';
function extractMarkdownDocumentTitle(markdown) {
    let inFence = false;
    let fenceMarker = '';
    for (const rawLine of String(markdown || '').split(/\r?\n/)) {
        const fenceMatch = rawLine.match(/^\s*(`{3,}|~{3,})/);
        if (fenceMatch) {
            const marker = fenceMatch[1][0];
            if (!inFence) {
                inFence = true;
                fenceMarker = marker;
                continue;
            }
            if (marker === fenceMarker) {
                inFence = false;
                fenceMarker = '';
                continue;
            }
        }
        if (inFence) {
            continue;
        }
        const titleMatch = rawLine.match(/^#\s+(.+?)\s*$/);
        if (!titleMatch) {
            continue;
        }
        return titleMatch[1].replace(/\s+#+\s*$/, '').trim();
    }
    return '';
}
function sanitizeDownloadTitle(value, fallback = DEFAULT_PDF_DOCUMENT_TITLE) {
    const sanitized = String(value || '')
        .replace(/[\u0000-\u001f\u007f\\/:*?"<>|]/g, ' ')
        .replace(/\s+/g, ' ')
        .trim()
        .replace(/[.\s]+$/g, '')
        .slice(0, 120)
        .trim();
    return sanitized || fallback;
}
function buildPdfDocumentTitle(markdown) {
    return sanitizeDownloadTitle(extractMarkdownDocumentTitle(markdown));
}

},
"src/web/markdown_normalizer": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.normalizeEditableMarkdown = normalizeEditableMarkdown;
function normalizeEditableMarkdown(markdown) {
    return String(markdown || '')
        .split(/(\r?\n)/)
        .map(part => {
        if (/^\r?\n$/.test(part)) {
            return part;
        }
        const match = part.match(/^([ \t]*)(#{3,})([ \t]*)(.*)$/);
        if (!match) {
            return part;
        }
        const [, indent, _hashes, space, text] = match;
        if (text.startsWith('-')) {
            return part;
        }
        return `${indent}##${space}${text}`;
    })
        .join('');
}

},
"src/web/app": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const court_markdown_1 = require("../base/court_markdown");
const document_title_1 = require("./document_title");
const markdown_normalizer_1 = require("./markdown_normalizer");
const paged_toc_1 = require("../lib/paged_toc");
const DEFAULT_MARKDOWN = `# 準備書面

### --目次

## 第1 請求の趣旨
原告の請求をいずれも棄却する。

## 第2 請求の原因に対する認否
1 原告の主張する契約締結の事実は否認する。

(1) 原告が提出する電子メールは、交渉経過の一部を示すものにすぎない。

(2) 代金額、納期、成果物の範囲について最終的な合意は成立していない。

## 第3 被告の主張
1 本件では、当事者間において契約の主要部分について合意がない。

2 仮に何らかの合意が認められるとしても、原告の主張する損害額は根拠を欠く。

### --右
令和8年5月31日
被告訴訟代理人弁護士　〇〇　〇〇
### --

以上
`;
const editor = document.getElementById('markdownInput');
const dropZone = document.getElementById('dropZone');
const fileInput = document.getElementById('fileInput');
const previewSurface = document.getElementById('previewSurface');
const previewViewport = document.getElementById('previewViewport');
const previewFrame = document.getElementById('previewFrame');
const statusText = document.getElementById('previewStatus');
const renderButton = document.getElementById('renderButton');
const htmlPreviewButton = document.getElementById('htmlPreviewButton');
const printButton = document.getElementById('printButton');
const pasteButton = document.getElementById('pasteButton');
const templateLoader = document.getElementById('templateLoader');
const templateSelect = document.getElementById('templateSelect');
const assetDropZone = document.getElementById('assetDropZone');
const imageFileButton = document.getElementById('imageFileButton');
const imageFolderButton = document.getElementById('imageFolderButton');
const imageFileInput = document.getElementById('imageFileInput');
const imageDirectoryInput = document.getElementById('imageDirectoryInput');
const imageAssetList = document.getElementById('imageAssetList');
let renderSeq = 0;
const IMAGE_EXTENSIONS = new Set(['.png', '.jpg', '.jpeg', '.gif', '.webp', '.svg']);
const imageAssets = new Map();
let currentMarkdownPath = '';
const PREVIEW_BASE_WIDTH = 840;
const PREVIEW_BASE_HEIGHT = 720;
const MIN_PREVIEW_SCALE = 0.18;
const MAX_PREVIEW_SCALE = 3;
let previewZoom = {
    scale: 1,
    fitScale: 1,
    manual: false,
    baseWidth: PREVIEW_BASE_WIDTH,
    baseHeight: PREVIEW_BASE_HEIGHT,
    startDistance: 0,
    startScale: 1,
};
function setStatus(message) {
    statusText.textContent = message;
}
function getDraftingTemplates() {
    const data = window.HOUHI_DRAFTING_DATA;
    return Array.isArray(data?.templates) ? data.templates : [];
}
function clamp(value, min, max) {
    return Math.max(min, Math.min(max, value));
}
function getTouchDistance(touches) {
    if (touches.length < 2)
        return 0;
    const dx = touches[0].clientX - touches[1].clientX;
    const dy = touches[0].clientY - touches[1].clientY;
    return Math.hypot(dx, dy);
}
function escapeScriptEnd(value) {
    return value.replace(/<\/script/gi, '<\\/script');
}
function escapeHtmlAttribute(value) {
    return value
        .replace(/&/g, '&amp;')
        .replace(/"/g, '&quot;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
}
function normalizeLocalPath(value) {
    return String(value || '')
        .replace(/\\/g, '/')
        .replace(/^\/+/, '')
        .replace(/^\.\//, '')
        .replace(/\/{2,}/g, '/')
        .trim();
}
function getExtname(value) {
    const name = normalizeLocalPath(value).split('/').pop() || '';
    const index = name.lastIndexOf('.');
    return index >= 0 ? name.slice(index).toLowerCase() : '';
}
function getBasename(value) {
    const normalized = normalizeLocalPath(value);
    return normalized.split('/').pop() || normalized;
}
function getDirname(value) {
    const normalized = normalizeLocalPath(value);
    const index = normalized.lastIndexOf('/');
    return index >= 0 ? normalized.slice(0, index) : '';
}
function joinLocalPath(base, leaf) {
    const raw = base ? `${base}/${leaf}` : leaf;
    const parts = normalizeLocalPath(raw).split('/').filter(Boolean);
    const out = [];
    for (const part of parts) {
        if (part === '.')
            continue;
        if (part === '..') {
            out.pop();
            continue;
        }
        out.push(part);
    }
    return out.join('/');
}
function relativeLocalPath(fromDir, toPath) {
    const fromParts = normalizeLocalPath(fromDir).split('/').filter(Boolean);
    const toParts = normalizeLocalPath(toPath).split('/').filter(Boolean);
    let common = 0;
    while (common < fromParts.length && common < toParts.length && fromParts[common] === toParts[common]) {
        common++;
    }
    const up = fromParts.slice(common).map(() => '..');
    const down = toParts.slice(common);
    const relative = [...up, ...down].join('/');
    return relative || getBasename(toPath);
}
function displayPathForAsset(asset) {
    if (!currentMarkdownPath) {
        return asset.sourcePath;
    }
    return relativeLocalPath(getDirname(currentMarkdownPath), asset.sourcePath);
}
function markdownTagForAsset(asset) {
    return `![説明](${displayPathForAsset(asset)})`;
}
function isImagePath(value) {
    return IMAGE_EXTENSIONS.has(getExtname(value));
}
function isExternalImageSrc(value) {
    return /^(?:https?:|data:|blob:|about:|#)/i.test(String(value || '').trim());
}
function decodeImageSrc(value) {
    const withoutHash = String(value || '').split('#')[0];
    const withoutQuery = withoutHash.split('?')[0];
    try {
        return decodeURIComponent(withoutQuery);
    }
    catch (_err) {
        return withoutQuery;
    }
}
function makeLocalInputFile(file, fallbackPath = '') {
    const filePath = file.webkitRelativePath || fallbackPath || file.name;
    return {
        file,
        path: normalizeLocalPath(filePath || file.name),
    };
}
function filesFromFileList(fileList) {
    return Array.from(fileList || []).map(file => makeLocalInputFile(file));
}
function fileFromEntry(entry) {
    return new Promise((resolve, reject) => {
        entry.file(resolve, reject);
    });
}
function readDirectoryEntries(reader) {
    return new Promise((resolve, reject) => {
        reader.readEntries(resolve, reject);
    });
}
async function collectEntryFiles(entry) {
    if (!entry) {
        return [];
    }
    if (entry.isFile) {
        const file = await fileFromEntry(entry);
        return [makeLocalInputFile(file, entry.fullPath || file.name)];
    }
    if (!entry.isDirectory) {
        return [];
    }
    const reader = entry.createReader();
    const files = [];
    for (;;) {
        const entries = await readDirectoryEntries(reader);
        if (!entries.length) {
            break;
        }
        for (const child of entries) {
            files.push(...await collectEntryFiles(child));
        }
    }
    return files;
}
async function collectDroppedFiles(dataTransfer) {
    if (!dataTransfer) {
        return [];
    }
    const items = Array.from(dataTransfer.items || []);
    const entries = items
        .map(item => typeof item.webkitGetAsEntry === 'function' ? item.webkitGetAsEntry() : null)
        .filter(Boolean);
    if (entries.length > 0) {
        const nested = await Promise.all(entries.map(entry => collectEntryFiles(entry)));
        return nested.flat();
    }
    return filesFromFileList(dataTransfer.files);
}
function resolveImageAsset(src) {
    const raw = decodeImageSrc(src);
    if (!raw || isExternalImageSrc(raw)) {
        return null;
    }
    const normalized = normalizeLocalPath(raw);
    const markdownDir = getDirname(currentMarkdownPath);
    const candidates = new Set([
        normalized,
        markdownDir ? joinLocalPath(markdownDir, normalized) : normalized,
    ]);
    for (const candidate of candidates) {
        const exact = imageAssets.get(candidate);
        if (exact) {
            return exact;
        }
    }
    for (const asset of imageAssets.values()) {
        if (displayPathForAsset(asset) === normalized) {
            return asset;
        }
    }
    const basename = getBasename(normalized);
    const basenameMatches = Array.from(imageAssets.values()).filter(asset => getBasename(asset.sourcePath) === basename);
    return basenameMatches.length === 1 ? basenameMatches[0] : null;
}
function prepareImageSources(bodyHtml) {
    const template = document.createElement('template');
    template.innerHTML = bodyHtml;
    for (const img of Array.from(template.content.querySelectorAll('img[src]'))) {
        const src = img.getAttribute('src') || '';
        const asset = resolveImageAsset(src);
        if (!asset) {
            img.setAttribute('data-houhi-image-missing', src);
            continue;
        }
        img.setAttribute('src', asset.url);
        img.setAttribute('data-houhi-source-path', displayPathForAsset(asset));
    }
    const container = document.createElement('div');
    container.appendChild(template.content.cloneNode(true));
    return container.innerHTML;
}
function waitForImages(frameDocument) {
    const images = Array.from(frameDocument.images || []);
    const pending = images
        .filter(img => !img.complete)
        .map(img => new Promise(resolve => {
        const done = () => resolve();
        img.addEventListener('load', done, { once: true });
        img.addEventListener('error', done, { once: true });
    }));
    if (!pending.length) {
        return Promise.resolve();
    }
    return Promise.race([
        Promise.all(pending).then(() => undefined),
        new Promise(resolve => (frameDocument.defaultView || window).setTimeout(resolve, 10000)),
    ]);
}
function addImageFiles(files) {
    let added = 0;
    for (const item of files) {
        if (!isImagePath(item.path || item.file.name)) {
            continue;
        }
        const sourcePath = normalizeLocalPath(item.path || item.file.name);
        const old = imageAssets.get(sourcePath);
        if (old) {
            URL.revokeObjectURL(old.url);
        }
        imageAssets.set(sourcePath, {
            file: item.file,
            sourcePath,
            url: URL.createObjectURL(item.file),
        });
        added++;
    }
    renderImageAssetList();
    return added;
}
function insertAtCursor(text) {
    const start = editor.selectionStart ?? editor.value.length;
    const end = editor.selectionEnd ?? editor.value.length;
    const before = editor.value.slice(0, start);
    const after = editor.value.slice(end);
    const prefix = before && !before.endsWith('\n') ? '\n' : '';
    const suffix = after && !after.startsWith('\n') ? '\n' : '';
    const insertion = `${prefix}${text}${suffix}`;
    editor.value = before + insertion + after;
    const cursor = before.length + insertion.length;
    editor.focus();
    editor.setSelectionRange(cursor, cursor);
    markPreviewDirty();
}
function renderImageAssetList() {
    imageAssetList.textContent = '';
    const assets = Array.from(imageAssets.values()).sort((a, b) => displayPathForAsset(a).localeCompare(displayPathForAsset(b), 'ja'));
    if (!assets.length) {
        const empty = document.createElement('p');
        empty.className = 'asset-empty';
        empty.textContent = '画像未読込';
        imageAssetList.appendChild(empty);
        return;
    }
    for (const asset of assets) {
        const row = document.createElement('div');
        row.className = 'image-asset-row';
        const thumb = document.createElement('img');
        thumb.className = 'image-asset-thumb';
        thumb.src = asset.url;
        thumb.alt = '';
        const meta = document.createElement('div');
        const name = document.createElement('div');
        name.className = 'image-asset-name';
        name.title = displayPathForAsset(asset);
        name.textContent = displayPathForAsset(asset);
        const code = document.createElement('code');
        code.className = 'image-asset-code';
        code.textContent = markdownTagForAsset(asset);
        meta.append(name, code);
        const insertButton = document.createElement('button');
        insertButton.type = 'button';
        insertButton.textContent = '挿入';
        insertButton.dataset.insertImagePath = displayPathForAsset(asset);
        row.append(thumb, meta, insertButton);
        imageAssetList.appendChild(row);
    }
}
function prepareTocPlaceholders(html) {
    return html.replace(/<cssj:make-toc\b[^>]*>\s*<\/cssj:make-toc>/gi, () => {
        return '<ul class="cssj-toc houhi-chrome-toc" data-houhi-chrome-toc="pending"></ul>';
    });
}
function buildPreviewDocument(markdown) {
    const bodyHtml = prepareTocPlaceholders(prepareImageSources((0, court_markdown_1.convertMarkdownToCourtHtml)(markdown)));
    const baseHref = new URL('./', window.location.href).href;
    const documentTitle = escapeHtmlAttribute((0, document_title_1.buildPdfDocumentTitle)(markdown));
    return `<!doctype html>
<html lang="ja" data-houhi-pdf-engine="chrome">
<head>
  <meta charset="utf-8">
  <title>${documentTitle}</title>
  <base href="${baseHref}">
  <link rel="stylesheet" href="court.css">
  <style>
    html, body { background: #fff; }
    body { padding: 0; }
    body, body * {
      font-family: "NotoSerifJP-Regular", "MS Mincho", "Hiragino Mincho ProN", serif;
    }
    .content-container { background: #fff; font-family: "NotoSerifJP-Regular", "MS Mincho", "Hiragino Mincho ProN", serif; }
    @media screen {
      html, body { overflow: auto; overscroll-behavior: contain; touch-action: pan-x pan-y; }
      .pagedjs_pages { margin: 24px auto; }
      .pagedjs_page { background: #fff; }
      .pagedjs_sheet { background: #fff; }
    }
  </style>
  <script>
    window.PagedConfig = window.PagedConfig || {};
    window.PagedConfig.auto = false;
  </script>
  <script src="vendor/paged.polyfill.min.js"></script>
</head>
<body>
  <main class="content-container">
${bodyHtml}
  </main>
  <script>
    window.__houhiPreviewSourceReady = true;
  </script>
</body>
</html>`;
}
function preparePlainHtmlBody(bodyHtml) {
    const template = document.createElement('template');
    template.innerHTML = bodyHtml;
    const tocItems = Array.from(template.content.querySelectorAll('li.heading-item h1, li.heading-item h2, li.heading-item h3, li.heading-item h4, li.heading-item h5, li.heading-item h6'))
        .map((heading, index) => {
        const id = `houhi-heading-${index + 1}`;
        heading.setAttribute('id', id);
        return {
            id,
            title: heading.textContent?.trim() || '',
        };
    })
        .filter(item => item.title.length > 0);
    const container = document.createElement('div');
    container.appendChild(template.content.cloneNode(true));
    const preparedHtml = container.innerHTML;
    const tocHtml = tocItems.length > 0
        ? `<ul class="cssj-toc plain-toc">${tocItems.map(item => `<li><a href="#${item.id}"><span class="cssj-title">${escapeHtmlAttribute(item.title)}</span></a></li>`).join('')}</ul>`
        : '';
    return preparedHtml.replace(/<cssj:make-toc\b[^>]*>\s*<\/cssj:make-toc>/gi, tocHtml);
}
function buildPlainHtmlDocument(markdown) {
    const bodyHtml = preparePlainHtmlBody(prepareImageSources((0, court_markdown_1.convertMarkdownToCourtHtml)(markdown)));
    const baseHref = new URL('./', window.location.href).href;
    return `<!doctype html>
<html lang="ja" data-houhi-pdf-engine="plain-html">
<head>
  <meta charset="utf-8">
  <base href="${baseHref}">
  <title>法匪 HTML表示</title>
  <link rel="stylesheet" href="court.css">
  <style>
    html {
      background: #f4f4f1;
      scroll-behavior: smooth;
    }
    body {
      margin: 0;
      background: #f4f4f1;
    }
    body:before {
      content: none;
    }
    body, body * {
      font-family: "NotoSerifJP-Regular", "MS Mincho", "Hiragino Mincho ProN", serif;
    }
    .content-container {
      box-sizing: border-box;
      max-width: 840px;
      min-height: 100vh;
      margin: 0 auto;
      padding: 42px 54px 84px;
      background: #fff;
      font-family: "NotoSerifJP-Regular", "MS Mincho", "Hiragino Mincho ProN", serif;
    }
    .break {
      margin: 2.2em 0;
      padding-top: 0.8em;
      border-top: 1px dashed #bbb;
      color: #666;
      text-align: center;
    }
    ul.plain-toc span.cssj-page,
    ul.plain-toc span.cssj-leader {
      display: none;
    }
    @media (max-width: 720px) {
      .content-container {
        padding: 28px 22px 64px;
      }
    }
  </style>
</head>
<body>
  <main class="content-container">
${bodyHtml}
  </main>
</body>
</html>`;
}
function waitForFrameLoad(frame) {
    return new Promise(resolve => {
        frame.addEventListener('load', () => resolve(), { once: true });
    });
}
function waitForPaged(frameWindow) {
    return new Promise((resolve, reject) => {
        const startedAt = Date.now();
        const check = () => {
            if (frameWindow.PagedPolyfill && typeof frameWindow.PagedPolyfill.preview === 'function') {
                resolve();
                return;
            }
            if (Date.now() - startedAt > 12000) {
                reject(new Error('Paged.js の読み込みがタイムアウトしました。'));
                return;
            }
            frameWindow.setTimeout(check, 50);
        };
        check();
    });
}
function nextFrame(frameWindow) {
    return new Promise(resolve => {
        frameWindow.requestAnimationFrame(() => {
            frameWindow.requestAnimationFrame(() => resolve());
        });
    });
}
function resetPreviewZoom() {
    previewZoom = {
        scale: 1,
        fitScale: 1,
        manual: false,
        baseWidth: PREVIEW_BASE_WIDTH,
        baseHeight: PREVIEW_BASE_HEIGHT,
        startDistance: 0,
        startScale: 1,
    };
    previewFrame.style.width = `${PREVIEW_BASE_WIDTH}px`;
    previewFrame.style.height = `${PREVIEW_BASE_HEIGHT}px`;
    previewFrame.style.transform = 'scale(1)';
    applyPreviewZoom();
}
function measurePreviewSize(frameDocument) {
    const pages = frameDocument.querySelector('.pagedjs_pages');
    const doc = frameDocument.documentElement;
    const body = frameDocument.body;
    const width = Math.ceil(Math.max(PREVIEW_BASE_WIDTH, pages?.scrollWidth || 0, pages?.offsetWidth || 0));
    const height = Math.ceil(Math.max(PREVIEW_BASE_HEIGHT, doc?.scrollHeight || 0, body?.scrollHeight || 0, pages?.scrollHeight || 0, pages?.offsetHeight || 0));
    return { width, height };
}
function applyPreviewZoom() {
    const baseWidth = Math.max(1, previewZoom.baseWidth);
    const baseHeight = Math.max(1, previewZoom.baseHeight);
    const availableWidth = Math.max(1, previewSurface.clientWidth - 32);
    const fitScale = clamp(Math.min(1, availableWidth / baseWidth), MIN_PREVIEW_SCALE, 1);
    previewZoom.fitScale = fitScale;
    previewZoom.scale = clamp(previewZoom.manual ? Math.max(previewZoom.scale, fitScale) : fitScale, fitScale, MAX_PREVIEW_SCALE);
    previewFrame.style.width = `${baseWidth}px`;
    previewFrame.style.height = `${baseHeight}px`;
    previewViewport.style.width = `${Math.ceil(baseWidth * previewZoom.scale)}px`;
    previewViewport.style.height = `${Math.ceil(baseHeight * previewZoom.scale)}px`;
    previewViewport.style.transform = 'none';
    previewFrame.style.transform = `scale(${previewZoom.scale.toFixed(4)})`;
}
function updatePreviewSize(frameDocument) {
    const size = measurePreviewSize(frameDocument);
    previewZoom.baseWidth = size.width;
    previewZoom.baseHeight = size.height;
    previewZoom.manual = false;
    applyPreviewZoom();
}
async function renderPreviewNow() {
    const seq = ++renderSeq;
    normalizeEditorMarkdownForRender();
    const markdown = editor.value.trim() ? editor.value : DEFAULT_MARKDOWN;
    setStatus('組版中...');
    renderButton.disabled = true;
    resetPreviewZoom();
    const loaded = waitForFrameLoad(previewFrame);
    previewFrame.srcdoc = buildPreviewDocument(markdown);
    await loaded;
    if (seq !== renderSeq)
        return;
    const frameWindow = previewFrame.contentWindow;
    const frameDocument = previewFrame.contentDocument;
    if (!frameWindow || !frameDocument) {
        setStatus('プレビューを作成できませんでした。');
        return;
    }
    try {
        await waitForPaged(frameWindow);
        await waitForImages(frameDocument);
        if (frameDocument.fonts && frameDocument.fonts.ready) {
            await frameDocument.fonts.ready;
        }
        await nextFrame(frameWindow);
        (0, paged_toc_1.prepareChromeToc)(frameDocument);
        await frameWindow.PagedPolyfill.preview();
        (0, paged_toc_1.fillChromeTocPageNumbers)(frameDocument);
        (0, paged_toc_1.applyManualPageNumbers)(frameDocument);
        updatePreviewSize(frameDocument);
        setStatus('プレビュー更新済み');
    }
    catch (err) {
        console.error(err);
        setStatus(err instanceof Error ? err.message : 'プレビュー作成中にエラーが発生しました。');
    }
    finally {
        renderButton.disabled = false;
    }
}
function markPreviewDirty() {
    setStatus('未更新');
}
function normalizeEditorMarkdownForRender() {
    const original = editor.value;
    const normalized = (0, markdown_normalizer_1.normalizeEditableMarkdown)(original);
    if (normalized === original) {
        return;
    }
    const selectionStart = editor.selectionStart ?? original.length;
    const selectionEnd = editor.selectionEnd ?? original.length;
    const nextSelectionStart = (0, markdown_normalizer_1.normalizeEditableMarkdown)(original.slice(0, selectionStart)).length;
    const nextSelectionEnd = (0, markdown_normalizer_1.normalizeEditableMarkdown)(original.slice(0, selectionEnd)).length;
    editor.value = normalized;
    editor.setSelectionRange(nextSelectionStart, nextSelectionEnd);
}
function getCurrentPdfDocumentTitle() {
    const markdown = editor.value.trim() ? editor.value : DEFAULT_MARKDOWN;
    return (0, document_title_1.buildPdfDocumentTitle)(markdown);
}
async function loadTemplate(template) {
    currentMarkdownPath = template.id;
    editor.value = template.content.trim();
    editor.focus();
    editor.setSelectionRange(0, 0);
    renderImageAssetList();
    setStatus(`${template.name} を読み込みました。`);
    await renderPreviewNow();
}
function setupTemplateLoader() {
    if (!templateLoader || !templateSelect) {
        return;
    }
    const templates = getDraftingTemplates();
    if (!templates.length) {
        return;
    }
    for (const template of templates) {
        const option = document.createElement('option');
        option.value = template.id;
        option.textContent = template.name;
        templateSelect.appendChild(option);
    }
    templateLoader.hidden = false;
    templateSelect.addEventListener('change', () => {
        const selected = templates.find(template => template.id === templateSelect.value);
        if (!selected) {
            editor.focus();
            return;
        }
        loadTemplate(selected).catch(err => {
            console.error(err);
            setStatus('テンプレートの読み込みに失敗しました。');
        });
    });
}
function openPlainHtmlPreview() {
    const markdown = editor.value.trim() ? editor.value : DEFAULT_MARKDOWN;
    const html = buildPlainHtmlDocument(markdown);
    const blob = new Blob([escapeScriptEnd(html)], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const tab = window.open('about:blank', '_blank');
    if (!tab) {
        URL.revokeObjectURL(url);
        setStatus('別タブを開けませんでした。ポップアップ許可を確認してください。');
        return;
    }
    tab.opener = null;
    tab.location.href = url;
    setStatus('HTML表示を別タブで開きました。');
    window.setTimeout(() => URL.revokeObjectURL(url), 60000);
}
async function pasteFromClipboard() {
    if (!navigator.clipboard || typeof navigator.clipboard.readText !== 'function') {
        editor.focus();
        setStatus('このブラウザではボタンから貼り付けできません。入力欄で貼り付けてください。');
        return;
    }
    pasteButton.disabled = true;
    try {
        const text = await navigator.clipboard.readText();
        if (!text.trim()) {
            editor.focus();
            setStatus('クリップボードにテキストがありません。');
            return;
        }
        editor.value = text;
        await renderPreviewNow();
    }
    catch (err) {
        console.error(err);
        editor.focus();
        setStatus('貼り付けを許可できませんでした。入力欄で貼り付けてください。');
    }
    finally {
        pasteButton.disabled = false;
    }
}
async function loadMarkdownFile(file, filePath = file.name) {
    if (!/\.md$/i.test(file.name)) {
        setStatus('.md ファイルを指定してください。');
        return;
    }
    currentMarkdownPath = normalizeLocalPath(filePath || file.name);
    editor.value = await file.text();
    setStatus(`${file.name} を読み込みました。`);
    renderImageAssetList();
    renderPreviewNow();
}
async function handleInputFiles(files) {
    const markdownFile = files.find(item => /\.md$/i.test(item.path || item.file.name));
    const imageCount = addImageFiles(files);
    if (markdownFile) {
        await loadMarkdownFile(markdownFile.file, markdownFile.path);
        if (imageCount > 0) {
            setStatus(`${markdownFile.file.name} と画像 ${imageCount} 件を読み込みました。`);
        }
        return;
    }
    if (imageCount > 0) {
        setStatus(`画像 ${imageCount} 件を読み込みました。`);
        await renderPreviewNow();
        return;
    }
    setStatus('.md または画像ファイルを指定してください。');
}
async function handleAssetFiles(files) {
    const imageCount = addImageFiles(files);
    if (imageCount > 0) {
        setStatus(`画像 ${imageCount} 件を読み込みました。`);
        await renderPreviewNow();
        return;
    }
    setStatus('画像ファイルを指定してください。');
}
editor.addEventListener('input', markPreviewDirty);
dropZone.addEventListener('dragover', event => {
    event.preventDefault();
    dropZone.classList.add('drag-over');
});
dropZone.addEventListener('dragleave', () => {
    dropZone.classList.remove('drag-over');
});
dropZone.addEventListener('drop', event => {
    event.preventDefault();
    dropZone.classList.remove('drag-over');
    collectDroppedFiles(event.dataTransfer).then(handleInputFiles).catch(err => {
        console.error(err);
        setStatus('ファイルの読み込みに失敗しました。');
    });
});
dropZone.addEventListener('click', () => fileInput.click());
fileInput.addEventListener('change', () => {
    const file = fileInput.files?.[0];
    if (file) {
        loadMarkdownFile(file, file.webkitRelativePath || file.name);
    }
});
assetDropZone.addEventListener('dragover', event => {
    event.preventDefault();
    assetDropZone.classList.add('drag-over');
});
assetDropZone.addEventListener('dragleave', () => {
    assetDropZone.classList.remove('drag-over');
});
assetDropZone.addEventListener('drop', event => {
    event.preventDefault();
    assetDropZone.classList.remove('drag-over');
    collectDroppedFiles(event.dataTransfer).then(handleAssetFiles).catch(err => {
        console.error(err);
        setStatus('画像の読み込みに失敗しました。');
    });
});
assetDropZone.addEventListener('click', () => imageFileInput.click());
imageFileButton.addEventListener('click', () => imageFileInput.click());
imageFolderButton.addEventListener('click', () => imageDirectoryInput.click());
imageFileInput.addEventListener('change', () => {
    handleAssetFiles(filesFromFileList(imageFileInput.files)).finally(() => {
        imageFileInput.value = '';
    });
});
imageDirectoryInput.addEventListener('change', () => {
    handleAssetFiles(filesFromFileList(imageDirectoryInput.files)).finally(() => {
        imageDirectoryInput.value = '';
    });
});
imageAssetList.addEventListener('click', event => {
    const target = event.target;
    const button = target.closest('button[data-insert-image-path]');
    if (!button) {
        return;
    }
    insertAtCursor(`![説明](${button.dataset.insertImagePath || ''})`);
});
pasteButton.addEventListener('click', pasteFromClipboard);
renderButton.addEventListener('click', renderPreviewNow);
htmlPreviewButton.addEventListener('click', openPlainHtmlPreview);
printButton.addEventListener('click', () => {
    const frameWindow = previewFrame.contentWindow;
    if (!frameWindow)
        return;
    const title = getCurrentPdfDocumentTitle();
    const oldTitle = document.title;
    document.title = title;
    if (frameWindow.document) {
        frameWindow.document.title = title;
    }
    const restoreTitle = () => {
        document.title = oldTitle;
        window.removeEventListener('focus', restoreTitle);
    };
    window.addEventListener('focus', restoreTitle, { once: true });
    window.setTimeout(restoreTitle, 30000);
    frameWindow.focus();
    frameWindow.print();
});
window.addEventListener('resize', applyPreviewZoom);
previewSurface.addEventListener('wheel', event => {
    if (!event.ctrlKey && !event.metaKey)
        return;
    event.preventDefault();
    previewZoom.manual = true;
    const factor = Math.exp(-event.deltaY * 0.0015);
    previewZoom.scale = clamp(previewZoom.scale * factor, previewZoom.fitScale, MAX_PREVIEW_SCALE);
    applyPreviewZoom();
}, { passive: false });
previewSurface.addEventListener('touchstart', event => {
    if (event.touches.length !== 2)
        return;
    previewZoom.startDistance = getTouchDistance(event.touches);
    previewZoom.startScale = previewZoom.scale;
}, { passive: true });
previewSurface.addEventListener('touchmove', event => {
    if (event.touches.length !== 2 || previewZoom.startDistance <= 0)
        return;
    event.preventDefault();
    previewZoom.manual = true;
    const distance = getTouchDistance(event.touches);
    previewZoom.scale = clamp(previewZoom.startScale * (distance / previewZoom.startDistance), previewZoom.fitScale, MAX_PREVIEW_SCALE);
    applyPreviewZoom();
}, { passive: false });
previewSurface.addEventListener('touchend', () => {
    previewZoom.startDistance = 0;
    previewZoom.startScale = previewZoom.scale;
});
previewSurface.addEventListener('touchcancel', () => {
    previewZoom.startDistance = 0;
    previewZoom.startScale = previewZoom.scale;
});
window.addEventListener('beforeunload', () => {
    for (const asset of imageAssets.values()) {
        URL.revokeObjectURL(asset.url);
    }
});
editor.value = DEFAULT_MARKDOWN;
setupTemplateLoader();
renderImageAssetList();
renderPreviewNow();

}
  };
  var cache = {};
  function resolve(from, request) {
    if (request.charAt(0) !== '.') return request;
    var parts = from.split('/');
    parts.pop();
    var raw = parts.concat(request.split('/'));
    var out = [];
    for (var i = 0; i < raw.length; i++) {
      var part = raw[i];
      if (!part || part === '.') continue;
      if (part === '..') out.pop();
      else out.push(part);
    }
    return out.join('/').replace(/\.(js|ts)$/, '');
  }
  function load(id) {
    if (cache[id]) return cache[id].exports;
    if (!modules[id]) throw new Error('Module not found: ' + id);
    var module = { exports: {} };
    cache[id] = module;
    modules[id](function (request) { return load(resolve(id, request)); }, module, module.exports);
    return module.exports;
  }
  load("src/web/app");
}());
