// Generated by scripts/build_web.js. Do not edit directly.
(function () {
  var modules = {
"src/base/court_markdown": function(require, module, exports) {
"use strict";
/**
 * 裁判文書用 Markdown -> HTML 変換スクリプト
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.convertMarkdownToCourtHtml = convertMarkdownToCourtHtml;
/**
 * 文字列の視覚的な幅（em単位）を計算します。
 * 半角文字を0.5em、全角文字を1emとして計算します。
 */
function getVisualWidth(text) {
    let width = 0;
    for (let i = 0; i < text.length; i++) {
        const code = text.charCodeAt(i);
        // 半角文字（ASCII, 半角カナ）は0.5、それ以外は1
        if ((code >= 0x0020 && code <= 0x007e) || (code >= 0xff61 && code <= 0xff9f)) {
            width += 0.5;
        }
        else {
            width += 1.0;
        }
    }
    return width;
}
function escapeHtmlAttribute(value) {
    return String(value)
        .replace(/&/g, '&amp;')
        .replace(/"/g, '&quot;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
}
/**
 * Markdownテキストを裁判文書用のHTMLに変換します。
 */
function convertMarkdownToCourtHtml(markdown) {
    const lines = markdown.split(/\r?\n/);
    let html = '';
    let lastLevel = 0;
    let inTable = false;
    let tableBuffer = [];
    let tableClass = '';
    let tableHasHeader = false;
    let inRightBlock = false;
    let inLeftBlock = false;
    let lastHeader = '';
    let inEvidenceTable = false;
    let evidenceTableBuffer = [];
    let inSimpleList = false;
    // インデント用のヘルパー
    const indent = (level) => '    '.repeat(level);
    const nl = '\n';
    const tocElement = '<cssj:make-toc xmlns:cssj="http://www.cssj.jp/ns/cssjml" counter="page" type="decimal"></cssj:make-toc>';
    const headingTag = (level) => `h${Math.min(Math.max(level, 1), 6)}`;
    // --- 事前スキャン: 各エリアのグローバルな列幅を計算 ---
    const rightColWidths = [];
    const leftColWidths = [];
    const attColWidths = [];
    const defaultColWidths = [];
    let scanHeader = '';
    let inScanEvidenceTable = false;
    let isSoufusho = false;
    let scanInRight = false;
    let scanInLeft = false;
    for (let line of lines) {
        const trimmed = line.trim();
        // ブロック検出
        if (trimmed === '### --右') {
            scanInRight = true;
            scanInLeft = false;
            continue;
        }
        if (trimmed === '### --左') {
            scanInLeft = true;
            scanInRight = false;
            continue;
        }
        if (trimmed === '### --') {
            scanInRight = false;
            scanInLeft = false;
            continue;
        }
        if (trimmed.startsWith('#')) {
            // 改ページマーカー等はヘッダーとして扱わない
            if (/^### --.*--$/.test(trimmed) || trimmed === '### ---' || trimmed === '### ...')
                continue;
            scanHeader = trimmed.replace(/^#*\s*/, '').trim();
            if (scanHeader === '送付書') {
                isSoufusho = true;
            }
        }
        const tableMatch = trimmed.match(/^\|(.*)\|$/);
        const listTableMatch = trimmed.match(/^[-*] (.*?)[：:](.*)$/);
        if (tableMatch || listTableMatch) {
            // 証拠説明書テーブルの開始を検出
            // 「号証」を含むヘッダー行を証拠説明書テーブルとして扱う
            if (tableMatch && (tableMatch[1].includes('号証'))) {
                inScanEvidenceTable = true;
            }
            // 証拠説明書テーブルは除外（別扱い）
            if (!inScanEvidenceTable) {
                // セパレーター行（|:---|:---|...）は除外
                if (tableMatch && /^[\s|:-]+$/.test(tableMatch[1])) {
                    continue;
                }
                let cells;
                if (tableMatch) {
                    cells = tableMatch[1].split('|');
                }
                else {
                    cells = [listTableMatch[1], listTableMatch[2]];
                }
                // どの幅配列を使うか決定
                let targetWidths = defaultColWidths;
                if (scanHeader === '附属書類' || scanHeader === '証拠書類') {
                    targetWidths = attColWidths;
                }
                else if (scanInRight) {
                    targetWidths = rightColWidths;
                }
                else if (scanInLeft) {
                    targetWidths = leftColWidths;
                }
                cells.forEach((cell, i) => {
                    const w = getVisualWidth(cell.trim());
                    if (!targetWidths[i] || w > targetWidths[i])
                        targetWidths[i] = w;
                });
            }
        }
        else if (inScanEvidenceTable) {
            // テーブル行以外が来たら証拠説明書テーブル終了
            inScanEvidenceTable = false;
        }
    }
    // テーブルをフラッシュしてHTMLを生成する内部関数
    const flushTable = () => {
        if (tableBuffer.length === 0)
            return '';
        let tableHtml = '';
        const effectiveClass = tableHasHeader ? tableClass + ' has-header' : tableClass;
        tableHtml += indent(lastLevel) + `<table class="${effectiveClass}">` + nl;
        const renderRow = (row, tag) => {
            let rowHtml = indent(lastLevel + 2) + '<tr>' + nl;
            row.forEach((cell, i) => {
                const text = cell.trim();
                const isAmount = tag === 'td' && i > 0 && /^[0-9０-９,，．.]+円?$/.test(text);
                const classes = [];
                if (tableClass.includes('info') || tableClass.includes('att'))
                    classes.push(`col-${i + 1}`);
                if (isAmount)
                    classes.push('val');
                const classAttr = classes.length > 0 ? ` class="${classes.join(' ')}"` : '';
                rowHtml += indent(lastLevel + 3) + `<${tag}${classAttr}>${text}</${tag}>` + nl;
            });
            rowHtml += indent(lastLevel + 2) + '</tr>' + nl;
            return rowHtml;
        };
        if (tableHasHeader && tableBuffer.length > 0) {
            tableHtml += indent(lastLevel + 1) + '<thead>' + nl;
            tableHtml += renderRow(tableBuffer[0], 'th');
            tableHtml += indent(lastLevel + 1) + '</thead>' + nl;
            tableHtml += indent(lastLevel + 1) + '<tbody>' + nl;
            tableBuffer.slice(1).forEach(row => { tableHtml += renderRow(row, 'td'); });
            tableHtml += indent(lastLevel + 1) + '</tbody>' + nl;
        }
        else {
            tableBuffer.forEach(row => { tableHtml += renderRow(row, 'td'); });
        }
        tableHtml += indent(lastLevel) + '</table>' + nl;
        tableBuffer = [];
        tableHasHeader = false;
        return tableHtml;
    };
    // 証拠説明書テーブルをフラッシュしてHTMLを生成する内部関数
    const flushEvidenceTable = () => {
        if (evidenceTableBuffer.length === 0)
            return '';
        let tableHtml = '';
        // ヘッダー行とセパレーター行をスキップ
        const headerRow = evidenceTableBuffer[0];
        const dataRows = evidenceTableBuffer.slice(1); // セパレーターは既に除外済みのためヘッダーのみスキップ
        tableHtml += indent(lastLevel) + '<table class="evidence">' + nl;
        // ヘッダー行を生成
        tableHtml += indent(lastLevel + 1) + '<thead>' + nl;
        tableHtml += indent(lastLevel + 2) + '<tr>' + nl;
        headerRow.forEach((cell, i) => {
            const text = cell.trim();
            tableHtml += indent(lastLevel + 3) + `<th class="col-${i + 1}">${text}</th>` + nl;
        });
        tableHtml += indent(lastLevel + 2) + '</tr>' + nl;
        tableHtml += indent(lastLevel + 1) + '</thead>' + nl;
        // データ行を生成
        tableHtml += indent(lastLevel + 1) + '<tbody>' + nl;
        // 各列で結合が必要な行を追跡
        const rowspanMap = new Map(); // key: colIndex, value: { rowIndex, span, text }
        dataRows.forEach((row, rowIndex) => {
            tableHtml += indent(lastLevel + 2) + '<tr>' + nl;
            row.forEach((cell, colIndex) => {
                const text = cell.trim();
                // この列が既に結合中かチェック
                if (rowspanMap.has(colIndex)) {
                    const info = rowspanMap.get(colIndex);
                    if (rowIndex < info.rowIndex + info.span) {
                        // まだ結合中なのでセルをスキップ
                        return;
                    }
                }
                // 空のセルの場合、上のセルと結合
                if (text === '') {
                    // 上方向に遡って最初の非空セルを探す
                    let spanCount = 1;
                    let lookupRow = rowIndex - 1;
                    let mergedText = '';
                    while (lookupRow >= 0) {
                        const prevText = dataRows[lookupRow][colIndex].trim();
                        if (prevText !== '') {
                            mergedText = prevText;
                            // 既存のrowspanを更新
                            if (rowspanMap.has(colIndex)) {
                                const existingInfo = rowspanMap.get(colIndex);
                                if (lookupRow >= existingInfo.rowIndex && lookupRow < existingInfo.rowIndex + existingInfo.span) {
                                    // 既存の結合を拡張
                                    existingInfo.span++;
                                    return;
                                }
                            }
                            // 新しいrowspanの開始位置まで遡る
                            let startRow = lookupRow;
                            while (startRow > 0 && dataRows[startRow - 1][colIndex].trim() === '') {
                                startRow--;
                                spanCount++;
                            }
                            // この空セルまでのスパンをカウント
                            spanCount = rowIndex - startRow + 1;
                            // 既存のマッピングを更新
                            if (rowspanMap.has(colIndex)) {
                                const info = rowspanMap.get(colIndex);
                                if (info.rowIndex === startRow) {
                                    info.span = spanCount + 1;
                                }
                            }
                            break;
                        }
                        lookupRow--;
                        spanCount++;
                    }
                    return; // 空のセルは出力しない
                }
                // 下方向に空のセルがいくつ続くかカウント
                let rowspan = 1;
                for (let nextRow = rowIndex + 1; nextRow < dataRows.length; nextRow++) {
                    if (dataRows[nextRow][colIndex].trim() === '') {
                        rowspan++;
                    }
                    else {
                        break;
                    }
                }
                if (rowspan > 1) {
                    rowspanMap.set(colIndex, { rowIndex, span: rowspan, text });
                }
                const rowspanAttr = rowspan > 1 ? ` rowspan="${rowspan}"` : '';
                tableHtml += indent(lastLevel + 3) + `<td class="col-${colIndex + 1}"${rowspanAttr}>${text}</td>` + nl;
            });
            tableHtml += indent(lastLevel + 2) + '</tr>' + nl;
        });
        tableHtml += indent(lastLevel + 1) + '</tbody>' + nl;
        tableHtml += indent(lastLevel) + '</table>' + nl;
        evidenceTableBuffer = [];
        return tableHtml;
    };
    const markers = [
        { level: 1, regex: /^#*\s*(第[0-9]+)[　\s]/ },
        { level: 2, regex: /^#*\s*([0-9]+)[　\s]/ },
        { level: 3, regex: /^#*\s*(\([0-9]+\))[　\s]/ },
        { level: 4, regex: /^#*\s*([ア-ン])[　\s]/ },
        { level: 5, regex: /^#*\s*(\([ア-ン]\))[　\s]/ },
        { level: 6, regex: /^#*\s*([a-z])[　\s]/ },
        { level: 7, regex: /^#*\s*(\([a-z]\))[　\s]/ }
    ];
    function getLevelInfo(line) {
        for (const m of markers) {
            const match = line.match(m.regex);
            if (match) {
                return { level: m.level, marker: match[1] };
            }
        }
        return null;
    }
    for (let line of lines) {
        const trimmedLine = line.trim();
        if (!trimmedLine)
            continue;
        // 右寄せ・左寄せブロックの開始・終了
        if (trimmedLine === '### --右') {
            if (inTable) {
                html += flushTable();
                inTable = false;
            }
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += '<div class="right">' + nl;
            inRightBlock = true;
            continue;
        }
        if (trimmedLine === '### --左') {
            if (inTable) {
                html += flushTable();
                inTable = false;
            }
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += '<div class="left">' + nl;
            inLeftBlock = true;
            continue;
        }
        if (trimmedLine === '### --') {
            if (inRightBlock || inLeftBlock) {
                if (inTable) {
                    html += flushTable();
                    inTable = false;
                }
                while (lastLevel > 0) {
                    html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                    lastLevel--;
                }
                html += '</div>' + nl;
                inRightBlock = false;
                inLeftBlock = false;
                continue;
            }
        }
        // テーブル行の処理: |書類名|通数| または - 書類名：通数
        const tableMatch = trimmedLine.match(/^\|(.*)\|$/);
        const listTableMatch = trimmedLine.match(/^[-*] (.*?)[：:](.*)$/);
        if (tableMatch || listTableMatch) {
            // セパレーター行（|:---|:---|...）をチェック
            const isSeparator = tableMatch && /^[\s|:-]+$/.test(tableMatch[1]);
            if (isSeparator) {
                tableHasHeader = true;
                continue;
            }
            // ヘッダー行（「号証」を含む）をチェック
            const isEvidenceHeader = tableMatch && tableMatch[1].includes('号証');
            if (isEvidenceHeader || (inEvidenceTable && tableMatch)) {
                // 証拠説明書テーブル
                if (!inEvidenceTable) {
                    while (lastLevel > 0) {
                        html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                        lastLevel--;
                    }
                    inEvidenceTable = true;
                }
                if (tableMatch) {
                    const cells = tableMatch[1].split('|');
                    evidenceTableBuffer.push(cells);
                }
                continue;
            }
            else if (!inTable) {
                // 通常のテーブル（info/att）
                while (lastLevel > 0) {
                    html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                    lastLevel--;
                }
                tableHasHeader = false;
                if (lastHeader === '附属書類' || lastHeader === '証拠書類') {
                    tableClass = 'att';
                }
                else if (inRightBlock) {
                    tableClass = 'info right-info';
                }
                else if (inLeftBlock) {
                    tableClass = 'info left-info';
                }
                else {
                    tableClass = 'info default-info';
                }
                inTable = true;
            }
            let cells;
            if (tableMatch) {
                cells = tableMatch[1].split('|');
            }
            else {
                cells = [listTableMatch[1], listTableMatch[2]];
            }
            tableBuffer.push(cells);
            continue;
        }
        else if (inTable) {
            html += flushTable();
            inTable = false;
        }
        else if (inEvidenceTable) {
            html += flushEvidenceTable();
            inEvidenceTable = false;
        }
        // シンプルなリスト形式の処理: * 項目名
        const simpleListMatch = trimmedLine.match(/^[*＊]\s+(.+)$/);
        if (simpleListMatch) {
            if (!inSimpleList) {
                while (lastLevel > 0) {
                    html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                    lastLevel--;
                }
                html += '<ul>' + nl;
                inSimpleList = true;
            }
            html += indent(1) + `<li>${simpleListMatch[1]}</li>` + nl;
            continue;
        }
        else if (inSimpleList) {
            html += '</ul>' + nl;
            inSimpleList = false;
        }
        // 画像の処理: ![説明](画像パス)
        // 書面では常に中央寄せの独立ブロックとして配置する
        const imageMatch = trimmedLine.match(/^!\[([^\]]*)\]\(([^)]+)\)$/);
        if (imageMatch) {
            if (inRightBlock || inLeftBlock) {
                while (lastLevel > 0) {
                    html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                    lastLevel--;
                }
                html += '</div>' + nl;
                inRightBlock = false;
                inLeftBlock = false;
            }
            const alt = escapeHtmlAttribute(imageMatch[1].trim());
            const src = escapeHtmlAttribute(imageMatch[2].trim());
            const currentIndent = indent(lastLevel + (lastLevel > 0 ? 1 : 0));
            html += currentIndent + `<div class="image-block"><img src="${src}" alt="${alt}" /></div>` + nl;
            continue;
        }
        // 空行（スペーサー）マーカーの処理: ### ...
        // 空行は入力上は捨てられるため、見た目の空行を挿入する
        if (trimmedLine === '### ...') {
            const currentIndent = indent(lastLevel + (lastLevel > 0 ? 1 : 0));
            html += currentIndent + '<div class="blank-line"></div>' + nl;
            continue;
        }
        // 目次マーカーの処理: ### 目次
        // Copper PDF の cssj:make-toc により、文書内の h1-h6 から目次を生成する
        if (trimmedLine === '### 目次') {
            if (inRightBlock || inLeftBlock) {
                while (lastLevel > 0) {
                    html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                    lastLevel--;
                }
                html += '</div>' + nl;
                inRightBlock = false;
                inLeftBlock = false;
            }
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += '<div class="toc-title">目次</div>' + nl;
            html += tocElement + nl;
            continue;
        }
        // 区切り線マーカーの処理: ### ---
        // 改ページはせず、点線（区切り線）を挿入する
        if (trimmedLine === '### ---') {
            // 右/左ブロック内で使われた場合も安全に閉じる
            if (inRightBlock || inLeftBlock) {
                while (lastLevel > 0) {
                    html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                    lastLevel--;
                }
                html += '</div>' + nl;
                inRightBlock = false;
                inLeftBlock = false;
            }
            // リストを閉じて区切り線を挿入
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += '<hr class="separator" />' + nl;
            continue;
        }
        // 改ページマーカーの処理: ### -- 任意のテキスト --
        if (/^### --.*--$/.test(trimmedLine)) {
            // テキスト部分を抽出
            const match = trimmedLine.match(/^### --\s*(.*?)\s*--$/);
            const breakText = match ? match[1].trim() : '';
            // リストを閉じて改ページを挿入
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += `<div class="break">(${breakText})</div>` + nl;
            continue;
        }
        const levelInfo = getLevelInfo(trimmedLine);
        const isHeader = trimmedLine.startsWith('#');
        const markerText = levelInfo
            ? trimmedLine.replace(/^#*\s*/, '').replace(levelInfo.marker, '').trim()
            : '';
        const isTocHeading = !!levelInfo && (isHeader || (levelInfo.level <= 2 && !markerText.includes('。')));
        const liClass = isTocHeading ? ' class="heading-item"' : '';
        let level, text;
        if (levelInfo) {
            level = levelInfo.level;
            // マーカーと#を除去
            text = markerText;
        }
        else {
            // マーカーがない場合は現在のレベルの継続（最初からマーカーがない場合はレベル0）
            level = lastLevel;
            text = trimmedLine.replace(/^#+\s*/, '').trim();
        }
        // 階層の調整
        let openedNewLevel = false;
        while (lastLevel < level) {
            if (lastLevel === 0) {
                lastLevel = level;
            }
            else {
                lastLevel++;
            }
            const currentLiClass = lastLevel === level ? liClass : '';
            html += indent(lastLevel - 1) + `<ol class="lvl${lastLevel}">` + nl + indent(lastLevel) + `<li${currentLiClass}>` + nl;
            openedNewLevel = true;
        }
        while (lastLevel > level) {
            html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
            lastLevel--;
        }
        if (lastLevel === level && levelInfo && !openedNewLevel) {
            // 新しいマーカーがある場合は次の li へ
            html += indent(lastLevel) + '</li>' + nl + indent(lastLevel) + `<li${liClass}>` + nl;
        }
        const currentIndent = indent(lastLevel + (lastLevel > 0 ? 1 : 0));
        if (isTocHeading) {
            lastHeader = text; // ヘッダテキストを保存
            if (levelInfo) {
                const tagName = headingTag(levelInfo.level);
                html += currentIndent + `<${tagName}>${levelInfo.marker}　${text}</${tagName}>` + nl;
            }
        }
        else if (isHeader) {
            lastHeader = text; // ヘッダテキストを保存
            // マーカーがないヘッダはリストの外に出し、文書タイトルとして扱う
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += `<div class="doc-title">${text}</div>` + nl;
        }
        else if (text === '以上') {
            // 「以上」のみの行は特別扱い（リストを閉じて右寄せ）
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += `<div class="end-mark">${text}</div>` + nl;
        }
        else if (text === '記') {
            // 「記」のみの行は特別扱い（リストを閉じてセンタリング）
            while (lastLevel > 0) {
                html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
                lastLevel--;
            }
            html += `<div class="center-mark">${text}</div>` + nl;
        }
        else if (/^(?:(?:令和|平成|昭和|大正|明治)\s*(?:[0-9０-９]{1,2}|[元〇○一二三四五六七八九十]{1,3})|[0-9０-９]{1,4})\s*年\s*(?:[0-9０-９]{1,2}|[〇○一二三四五六七八九十]{1,3})\s*月\s*(?:[0-9０-９]{1,2}|[元〇○一二三四五六七八九十]{1,3})\s*日$/.test(text)) {
            // 日付の識別 (和暦・西暦、数字・漢数字、元年などに対応)
            html += currentIndent + `<div class="date">${text}</div>` + nl;
        }
        else if (/.*[　\s](?:御中|様)$/.test(text)) {
            // 宛先の識別
            html += currentIndent + `<div class="dest">${text}</div>` + nl;
        }
        else {
            html += currentIndent + `<p>${text}</p>` + nl;
        }
        lastLevel = level;
    }
    // 残ったタグを閉じる
    if (inTable) {
        html += flushTable();
    }
    if (inEvidenceTable) {
        html += flushEvidenceTable();
    }
    if (inSimpleList) {
        html += '</ul>' + nl;
    }
    while (lastLevel > 0) {
        html += indent(lastLevel - 1) + '</li>' + nl + indent(lastLevel - 1) + '</ol>' + nl;
        lastLevel--;
    }
    // スタイルを生成
    let styleTag = '';
    if (rightColWidths.length > 0 || leftColWidths.length > 0 || attColWidths.length > 0 || defaultColWidths.length > 0 || isSoufusho) {
        styleTag = '<style>' + nl;
        if (isSoufusho) {
            styleTag += '* { font-size: 10.5pt; }' + nl;
        }
        const generateTableStyle = (widths, className) => {
            let css = '';
            widths.forEach((w, i) => {
                if (w) {
                    w += 1; // 余裕を持たせる
                    // 附属書類・証拠書類（attクラス）の1列目はカウンター（2em）があるため幅を広げる
                    if (className === 'att' && i === 0) {
                        w += 2.5;
                    }
                    css += `table.${className} td.col-${i + 1} { width: ${w}em; }` + nl;
                }
            });
            return css;
        };
        styleTag += generateTableStyle(rightColWidths, 'right-info');
        styleTag += generateTableStyle(leftColWidths, 'left-info');
        styleTag += generateTableStyle(attColWidths, 'att');
        styleTag += generateTableStyle(defaultColWidths, 'default-info'); // クラス指定がない通常のinfoテーブル用
        styleTag += '</style>' + nl;
    }
    return styleTag + html;
}
/**
 * ページ内のすべての <pre> タグを裁判文書形式に変換します。
 */
async function renderMarkdown() {
    const preElements = document.querySelectorAll('pre');
    for (const pre of Array.from(preElements)) {
        let markdown = pre.textContent;
        const src = pre.getAttribute('data-src');
        if (src) {
            try {
                const response = await fetch(src);
                if (response.ok) {
                    markdown = await response.text();
                }
                else {
                    console.error(`Failed to load markdown from ${src}: ${response.status}`);
                }
            }
            catch (e) {
                console.error(`Error fetching markdown from ${src}:`, e);
            }
        }
        if (!markdown.trim())
            continue;
        const html = convertMarkdownToCourtHtml(markdown);
        // pre要素を変換後のHTMLで置き換える
        const container = document.createElement('div');
        container.className = (pre.className ? pre.className + ' ' : '') + 'content-container';
        container.innerHTML = html;
        pre.parentNode.replaceChild(container, pre);
    }
}
// Node.js環境用のエクスポート
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { convertMarkdownToCourtHtml };
}
else {
    window.convertMarkdownToCourtHtml = convertMarkdownToCourtHtml;
    // ブラウザ環境では自動実行
    window.__houhiMarkdownReady = false;
    window.__houhiMarkdownPromise = null;
    document.addEventListener('DOMContentLoaded', () => {
        const promise = renderMarkdown();
        window.__houhiMarkdownPromise = promise;
        promise.finally(() => {
            window.__houhiMarkdownReady = true;
        });
    });
}

},
"src/lib/paged_toc": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.prepareChromeToc = prepareChromeToc;
exports.fillChromeTocPageNumbers = fillChromeTocPageNumbers;
exports.applyManualPageNumbers = applyManualPageNumbers;
exports.getPagedTocBrowserScript = getPagedTocBrowserScript;
function prepareChromeToc(root = document) {
    const tocRoots = Array.prototype.slice.call(root.querySelectorAll('[data-houhi-chrome-toc]'));
    if (tocRoots.length === 0)
        return;
    const headings = Array.prototype.slice.call(root.querySelectorAll('h1, h2'));
    const targetHeadings = headings.filter(heading => !heading.closest('[data-houhi-chrome-toc]'));
    targetHeadings.forEach((heading, index) => {
        if (!heading.getAttribute('data-houhi-toc-id')) {
            heading.setAttribute('data-houhi-toc-id', `houhi-toc-${index + 1}`);
        }
    });
    tocRoots.forEach(tocRoot => {
        tocRoot.innerHTML = '';
        tocRoot.setAttribute('data-houhi-chrome-toc', 'ready');
        let currentLevel1Item = null;
        targetHeadings.forEach(heading => {
            const isLevel2 = heading.tagName.toLowerCase() === 'h2';
            const li = root.createElement('li');
            li.setAttribute('data-houhi-toc-target', heading.getAttribute('data-houhi-toc-id') || '');
            const link = root.createElement('a');
            const title = root.createElement('span');
            title.className = 'cssj-title';
            title.textContent = (heading.textContent || '').trim();
            const page = root.createElement('span');
            page.className = 'cssj-page';
            page.textContent = ' ';
            const leader = root.createElement('span');
            leader.className = 'cssj-leader';
            link.appendChild(title);
            link.appendChild(leader);
            link.appendChild(page);
            li.appendChild(link);
            if (isLevel2 && currentLevel1Item) {
                let nested = currentLevel1Item.querySelector(':scope > ul');
                if (!nested) {
                    nested = root.createElement('ul');
                    currentLevel1Item.appendChild(nested);
                }
                nested.appendChild(li);
            }
            else {
                tocRoot.appendChild(li);
                currentLevel1Item = isLevel2 ? null : li;
            }
        });
    });
}
function cssEscape(value) {
    const cssApi = globalThis.CSS;
    if (cssApi && typeof cssApi.escape === 'function') {
        return cssApi.escape(value);
    }
    return value.replace(/["\\]/g, '\\$&');
}
function findPagedCloneForSource(root, source) {
    const ref = source && source.getAttribute('data-ref');
    if (ref) {
        const clone = root.querySelector(`.pagedjs_pages [data-ref="${cssEscape(ref)}"]`);
        if (clone)
            return clone;
    }
    const tocId = source && source.getAttribute('data-houhi-toc-id');
    if (tocId) {
        return root.querySelector(`.pagedjs_pages [data-houhi-toc-id="${cssEscape(tocId)}"]`);
    }
    return null;
}
function getPageNumberForElement(element) {
    const page = element && element.closest('.pagedjs_page');
    if (!page)
        return '';
    return page.getAttribute('data-page-number') || page.dataset.pageNumber || '';
}
function fillChromeTocPageNumbers(root = document) {
    const sourceById = {};
    Array.prototype.forEach.call(root.querySelectorAll('h1[data-houhi-toc-id], h2[data-houhi-toc-id]'), (heading) => {
        sourceById[heading.getAttribute('data-houhi-toc-id') || ''] = heading;
    });
    Array.prototype.forEach.call(root.querySelectorAll('.pagedjs_pages [data-houhi-chrome-toc] li[data-houhi-toc-target]'), (item) => {
        const targetId = item.getAttribute('data-houhi-toc-target') || '';
        const source = sourceById[targetId];
        const clone = findPagedCloneForSource(root, source);
        const pageNumber = getPageNumberForElement(clone);
        const pageSpan = item.querySelector('.cssj-page');
        if (pageSpan && pageNumber) {
            pageSpan.textContent = pageNumber;
        }
    });
}
function applyManualPageNumbers(root = document) {
    const pageNumberStyle = root.createElement('style');
    pageNumberStyle.setAttribute('data-houhi-pagedjs-page-numbers', 'manual');
    pageNumberStyle.textContent = 'html[data-houhi-pdf-engine="chrome"] body::before { content: none !important; display: none !important; } @page { @bottom-center { content: none; } } .pagedjs_pages .pagedjs_margin-bottom .pagedjs_margin-bottom-center .pagedjs_margin-content::after { content: none !important; }';
    root.head.appendChild(pageNumberStyle);
    Array.prototype.forEach.call(root.querySelectorAll('.pagedjs_page'), (page, index) => {
        const footer = page.querySelector('.pagedjs_margin-bottom-center .pagedjs_margin-content');
        if (footer) {
            if (footer.parentElement) {
                footer.parentElement.classList.add('hasContent');
            }
            footer.textContent = `- ${index + 1} -`;
        }
    });
}
function getPagedTocBrowserScript() {
    return `
var cssEscape = ${cssEscape.toString()};
var findPagedCloneForSource = ${findPagedCloneForSource.toString()};
var getPageNumberForElement = ${getPageNumberForElement.toString()};
function prepareChromeToc(){(${prepareChromeToc.toString()})(document);}
function fillChromeTocPageNumbers(){(${fillChromeTocPageNumbers.toString()})(document);}
function applyManualPageNumbers(){(${applyManualPageNumbers.toString()})(document);}
`.trim();
}

},
"src/web/app": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const court_markdown_1 = require("../base/court_markdown");
const paged_toc_1 = require("../lib/paged_toc");
const DEFAULT_MARKDOWN = `# 準備書面

### 目次

## 第1 請求の趣旨
原告の請求をいずれも棄却する。

## 第2 請求の原因に対する認否
1 原告の主張する契約締結の事実は否認する。

(1) 原告が提出する電子メールは、交渉経過の一部を示すものにすぎない。

(2) 代金額、納期、成果物の範囲について最終的な合意は成立していない。

## 第3 被告の主張
1 本件では、当事者間において契約の主要部分について合意がない。

2 仮に何らかの合意が認められるとしても、原告の主張する損害額は根拠を欠く。

### --右
令和8年5月31日
被告訴訟代理人弁護士　〇〇　〇〇
### --

以上
`;
const editor = document.getElementById('markdownInput');
const dropZone = document.getElementById('dropZone');
const fileInput = document.getElementById('fileInput');
const previewFrame = document.getElementById('previewFrame');
const statusText = document.getElementById('previewStatus');
const renderButton = document.getElementById('renderButton');
const htmlPreviewButton = document.getElementById('htmlPreviewButton');
const printButton = document.getElementById('printButton');
const pasteButton = document.getElementById('pasteButton');
let renderSeq = 0;
function setStatus(message) {
    statusText.textContent = message;
}
function escapeScriptEnd(value) {
    return value.replace(/<\/script/gi, '<\\/script');
}
function escapeHtmlAttribute(value) {
    return value
        .replace(/&/g, '&amp;')
        .replace(/"/g, '&quot;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;');
}
function prepareTocPlaceholders(html) {
    return html.replace(/<cssj:make-toc\b[^>]*>\s*<\/cssj:make-toc>/gi, () => {
        return '<ul class="cssj-toc houhi-chrome-toc" data-houhi-chrome-toc="pending"></ul>';
    });
}
function buildPreviewDocument(markdown) {
    const bodyHtml = prepareTocPlaceholders((0, court_markdown_1.convertMarkdownToCourtHtml)(markdown));
    const baseHref = new URL('./', window.location.href).href;
    return `<!doctype html>
<html lang="ja" data-houhi-pdf-engine="chrome">
<head>
  <meta charset="utf-8">
  <base href="${baseHref}">
  <link rel="stylesheet" href="court.css">
  <style>
    html, body { background: #fff; }
    body { padding: 0; }
    body, body * {
      font-family: "NotoSerifJP-Regular", "MS Mincho", "Hiragino Mincho ProN", serif;
    }
    .content-container { background: #fff; font-family: "NotoSerifJP-Regular", "MS Mincho", "Hiragino Mincho ProN", serif; }
    @media screen {
      .pagedjs_pages { margin: 24px auto; }
      .pagedjs_page { background: #fff; }
      .pagedjs_sheet { background: #fff; }
    }
  </style>
  <script>
    window.PagedConfig = window.PagedConfig || {};
    window.PagedConfig.auto = false;
  </script>
  <script src="vendor/paged.polyfill.min.js"></script>
</head>
<body>
  <main class="content-container">
${bodyHtml}
  </main>
  <script>
    window.__houhiPreviewSourceReady = true;
  </script>
</body>
</html>`;
}
function preparePlainHtmlBody(bodyHtml) {
    const template = document.createElement('template');
    template.innerHTML = bodyHtml;
    const tocItems = Array.from(template.content.querySelectorAll('li.heading-item h1, li.heading-item h2, li.heading-item h3, li.heading-item h4, li.heading-item h5, li.heading-item h6'))
        .map((heading, index) => {
        const id = `houhi-heading-${index + 1}`;
        heading.setAttribute('id', id);
        return {
            id,
            title: heading.textContent?.trim() || '',
        };
    })
        .filter(item => item.title.length > 0);
    const container = document.createElement('div');
    container.appendChild(template.content.cloneNode(true));
    const preparedHtml = container.innerHTML;
    const tocHtml = tocItems.length > 0
        ? `<ul class="cssj-toc plain-toc">${tocItems.map(item => `<li><a href="#${item.id}"><span class="cssj-title">${escapeHtmlAttribute(item.title)}</span></a></li>`).join('')}</ul>`
        : '';
    return preparedHtml.replace(/<cssj:make-toc\b[^>]*>\s*<\/cssj:make-toc>/gi, tocHtml);
}
function buildPlainHtmlDocument(markdown) {
    const bodyHtml = preparePlainHtmlBody((0, court_markdown_1.convertMarkdownToCourtHtml)(markdown));
    const baseHref = new URL('./', window.location.href).href;
    return `<!doctype html>
<html lang="ja" data-houhi-pdf-engine="plain-html">
<head>
  <meta charset="utf-8">
  <base href="${baseHref}">
  <title>法匪 HTML表示</title>
  <link rel="stylesheet" href="court.css">
  <style>
    html {
      background: #f4f4f1;
      scroll-behavior: smooth;
    }
    body {
      margin: 0;
      background: #f4f4f1;
    }
    body:before {
      content: none;
    }
    body, body * {
      font-family: "NotoSerifJP-Regular", "MS Mincho", "Hiragino Mincho ProN", serif;
    }
    .content-container {
      box-sizing: border-box;
      max-width: 840px;
      min-height: 100vh;
      margin: 0 auto;
      padding: 42px 54px 84px;
      background: #fff;
      font-family: "NotoSerifJP-Regular", "MS Mincho", "Hiragino Mincho ProN", serif;
    }
    .break {
      margin: 2.2em 0;
      padding-top: 0.8em;
      border-top: 1px dashed #bbb;
      color: #666;
      text-align: center;
    }
    ul.plain-toc span.cssj-page,
    ul.plain-toc span.cssj-leader {
      display: none;
    }
    @media (max-width: 720px) {
      .content-container {
        padding: 28px 22px 64px;
      }
    }
  </style>
</head>
<body>
  <main class="content-container">
${bodyHtml}
  </main>
</body>
</html>`;
}
function waitForFrameLoad(frame) {
    return new Promise(resolve => {
        frame.addEventListener('load', () => resolve(), { once: true });
    });
}
function waitForPaged(frameWindow) {
    return new Promise((resolve, reject) => {
        const startedAt = Date.now();
        const check = () => {
            if (frameWindow.PagedPolyfill && typeof frameWindow.PagedPolyfill.preview === 'function') {
                resolve();
                return;
            }
            if (Date.now() - startedAt > 12000) {
                reject(new Error('Paged.js の読み込みがタイムアウトしました。'));
                return;
            }
            frameWindow.setTimeout(check, 50);
        };
        check();
    });
}
function nextFrame(frameWindow) {
    return new Promise(resolve => {
        frameWindow.requestAnimationFrame(() => {
            frameWindow.requestAnimationFrame(() => resolve());
        });
    });
}
async function renderPreviewNow() {
    const seq = ++renderSeq;
    const markdown = editor.value.trim() ? editor.value : DEFAULT_MARKDOWN;
    setStatus('組版中...');
    renderButton.disabled = true;
    const loaded = waitForFrameLoad(previewFrame);
    previewFrame.srcdoc = buildPreviewDocument(markdown);
    await loaded;
    if (seq !== renderSeq)
        return;
    const frameWindow = previewFrame.contentWindow;
    const frameDocument = previewFrame.contentDocument;
    if (!frameWindow || !frameDocument) {
        setStatus('プレビューを作成できませんでした。');
        return;
    }
    try {
        await waitForPaged(frameWindow);
        if (frameDocument.fonts && frameDocument.fonts.ready) {
            await frameDocument.fonts.ready;
        }
        await nextFrame(frameWindow);
        (0, paged_toc_1.prepareChromeToc)(frameDocument);
        await frameWindow.PagedPolyfill.preview();
        (0, paged_toc_1.fillChromeTocPageNumbers)(frameDocument);
        (0, paged_toc_1.applyManualPageNumbers)(frameDocument);
        setStatus('プレビュー更新済み');
    }
    catch (err) {
        console.error(err);
        setStatus(err instanceof Error ? err.message : 'プレビュー作成中にエラーが発生しました。');
    }
    finally {
        renderButton.disabled = false;
    }
}
function markPreviewDirty() {
    setStatus('未更新');
}
function openPlainHtmlPreview() {
    const markdown = editor.value.trim() ? editor.value : DEFAULT_MARKDOWN;
    const html = buildPlainHtmlDocument(markdown);
    const blob = new Blob([escapeScriptEnd(html)], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const tab = window.open('about:blank', '_blank');
    if (!tab) {
        URL.revokeObjectURL(url);
        setStatus('別タブを開けませんでした。ポップアップ許可を確認してください。');
        return;
    }
    tab.opener = null;
    tab.location.href = url;
    setStatus('HTML表示を別タブで開きました。');
    window.setTimeout(() => URL.revokeObjectURL(url), 60000);
}
async function pasteFromClipboard() {
    if (!navigator.clipboard || typeof navigator.clipboard.readText !== 'function') {
        editor.focus();
        setStatus('このブラウザではボタンから貼り付けできません。入力欄で貼り付けてください。');
        return;
    }
    pasteButton.disabled = true;
    try {
        const text = await navigator.clipboard.readText();
        if (!text.trim()) {
            editor.focus();
            setStatus('クリップボードにテキストがありません。');
            return;
        }
        editor.value = text;
        await renderPreviewNow();
    }
    catch (err) {
        console.error(err);
        editor.focus();
        setStatus('貼り付けを許可できませんでした。入力欄で貼り付けてください。');
    }
    finally {
        pasteButton.disabled = false;
    }
}
async function loadFile(file) {
    if (!/\.md$/i.test(file.name)) {
        setStatus('.md ファイルを指定してください。');
        return;
    }
    editor.value = await file.text();
    setStatus(`${file.name} を読み込みました。`);
    renderPreviewNow();
}
editor.addEventListener('input', markPreviewDirty);
dropZone.addEventListener('dragover', event => {
    event.preventDefault();
    dropZone.classList.add('drag-over');
});
dropZone.addEventListener('dragleave', () => {
    dropZone.classList.remove('drag-over');
});
dropZone.addEventListener('drop', event => {
    event.preventDefault();
    dropZone.classList.remove('drag-over');
    const file = event.dataTransfer?.files?.[0];
    if (file) {
        loadFile(file);
    }
});
dropZone.addEventListener('click', () => fileInput.click());
fileInput.addEventListener('change', () => {
    const file = fileInput.files?.[0];
    if (file) {
        loadFile(file);
    }
});
pasteButton.addEventListener('click', pasteFromClipboard);
renderButton.addEventListener('click', renderPreviewNow);
htmlPreviewButton.addEventListener('click', openPlainHtmlPreview);
printButton.addEventListener('click', () => {
    const frameWindow = previewFrame.contentWindow;
    if (!frameWindow)
        return;
    frameWindow.focus();
    frameWindow.print();
});
editor.value = DEFAULT_MARKDOWN;
renderPreviewNow();

}
  };
  var cache = {};
  function resolve(from, request) {
    if (request.charAt(0) !== '.') return request;
    var parts = from.split('/');
    parts.pop();
    var raw = parts.concat(request.split('/'));
    var out = [];
    for (var i = 0; i < raw.length; i++) {
      var part = raw[i];
      if (!part || part === '.') continue;
      if (part === '..') out.pop();
      else out.push(part);
    }
    return out.join('/').replace(/\.(js|ts)$/, '');
  }
  function load(id) {
    if (cache[id]) return cache[id].exports;
    if (!modules[id]) throw new Error('Module not found: ' + id);
    var module = { exports: {} };
    cache[id] = module;
    modules[id](function (request) { return load(resolve(id, request)); }, module, module.exports);
    return module.exports;
  }
  load("src/web/app");
}());
