// Generated by scripts/build_web.js. Do not edit directly.
(function () {
  var modules = {
"src/lib/ai_archive/case_index_renderer": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildCaseIndex = buildCaseIndex;
const utils_1 = require("./utils");
function getReadingPriority(file) {
    const kind = file.documentKind;
    if (/訴状|答弁書|準備書面|控訴|上告/.test(kind))
        return 10;
    if (/証拠説明書/.test(kind))
        return 20;
    if (/告訴状|行政手続書面|申立書/.test(kind))
        return 25;
    if (/反訳書/.test(kind))
        return 30;
    if (/証拠資料/.test(kind))
        return 40;
    if (/メモ/.test(kind))
        return 50;
    return 60;
}
function buildCaseIndex(caseName, scan) {
    const sortedFiles = [...scan.caseFiles].sort((a, b) => {
        const priorityDiff = getReadingPriority(a) - getReadingPriority(b);
        if (priorityDiff !== 0)
            return priorityDiff;
        return (0, utils_1.compareInstructionPaths)(a.relativePath, b.relativePath);
    });
    const readingOrder = sortedFiles
        .map((file, index) => {
        const evidence = file.evidenceNumber ? ` / 証拠番号: ${file.evidenceNumber}` : '';
        const dates = file.dateCandidates.length > 0 ? ` / 日付候補: ${file.dateCandidates.join(', ')}` : '';
        return `${index + 1}. \`${file.displayPath}\` - ${file.documentKind}${evidence}${dates}`;
    })
        .join('\n');
    const fileRows = scan.caseFiles
        .map(file => {
        return `| \`${(0, utils_1.escapeMarkdownTableCell)(file.displayPath)}\` | ${(0, utils_1.escapeMarkdownTableCell)(file.documentKind)} | ${(0, utils_1.escapeMarkdownTableCell)(file.evidenceNumber)} | ${(0, utils_1.escapeMarkdownTableCell)(file.dateCandidates.join(', '))} | ${(0, utils_1.escapeMarkdownTableCell)((0, utils_1.formatBytes)(file.sizeBytes))} | ${(0, utils_1.escapeMarkdownTableCell)(file.lineCount)} | ${(0, utils_1.escapeMarkdownTableCell)(file.warnings.length > 0 ? file.warnings.join('<br>') : '')} |`;
    })
        .join('\n');
    const skippedSection = scan.skippedFiles.length > 0
        ? `
## ZIPに含めなかったファイル

このツールは \`.md\` / \`.txt\` だけをAI用本文資料として収録します。以下のファイルは元フォルダに存在しましたが、ZIPには含めていません。

| 元パス | 拡張子 | サイズ | 理由 |
| --- | --- | ---: | --- |
${scan.skippedFiles.map(file => `| \`${(0, utils_1.escapeMarkdownTableCell)(file.relativePath)}\` | ${(0, utils_1.escapeMarkdownTableCell)(file.extension || '(なし)')} | ${(0, utils_1.escapeMarkdownTableCell)((0, utils_1.formatBytes)(file.sizeBytes))} | ${(0, utils_1.escapeMarkdownTableCell)(file.reason)} |`).join('\n')}
`
        : '';
    return `# CASE_INDEX - 事件資料目録

元フォルダ名: \`${caseName}\`

## 読み方

- 事件の事実関係は \`${scan.caseRoot}/\` 配下のファイルから把握してください。
- \`instructions/\` は起案用の参照資料であり、事件資料ではありません。
- 下記の種別、証拠番号、日付候補はファイル名と本文冒頭からの自動推定です。必要に応じて本文で確認してください。

## 推奨読解順

${readingOrder || '- 事件資料ファイルがありません。'}

## 事件資料一覧

| パス | 推定種別 | 証拠番号 | 日付候補 | サイズ | 行数 | 注意 |
| --- | --- | --- | --- | ---: | ---: | --- |
${fileRows || '| - | - | - | - | - | - | - |'}
${skippedSection}
`;
}

},
"src/lib/ai_archive/constants": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MAX_SKIPPED_FILES_IN_WARNING = exports.MAX_DATE_CANDIDATES = exports.VERY_SHORT_TEXT_CHARS = exports.LARGE_TEXT_FILE_BYTES = exports.CASE_DOCUMENTS_ROOT = void 0;
exports.CASE_DOCUMENTS_ROOT = 'case';
exports.LARGE_TEXT_FILE_BYTES = 250 * 1024;
exports.VERY_SHORT_TEXT_CHARS = 20;
exports.MAX_DATE_CANDIDATES = 5;
exports.MAX_SKIPPED_FILES_IN_WARNING = 20;

},
"src/lib/ai_archive/inference": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.normalizeEvidenceNumber = normalizeEvidenceNumber;
exports.extractEvidenceNumber = extractEvidenceNumber;
exports.extractDateCandidates = extractDateCandidates;
exports.inferDocumentKind = inferDocumentKind;
exports.buildFileWarnings = buildFileWarnings;
const constants_1 = require("./constants");
const utils_1 = require("./utils");
function toHalfWidthDigits(value) {
    return value.replace(/[０-９]/g, char => String.fromCharCode(char.charCodeAt(0) - 0xfee0));
}
function normalizeEvidenceNumber(value) {
    const compact = toHalfWidthDigits(value.replace(/\s+/g, ''));
    const match = compact.match(/^([甲乙丙丁戊疎証])(?:第)?([0-9]+(?:[-ー－の][0-9]+)?)(?:号証|号)?$/);
    if (!match) {
        return compact;
    }
    return `${match[1]}${match[2].replace(/[ー－]/g, '-')}`;
}
function extractEvidenceNumber(relativePath, text) {
    const searchText = `${relativePath}\n${text.slice(0, 2000)}`;
    const match = searchText.match(/(?:^|[\/\s_\-（(])([甲乙丙丁戊疎証]\s*(?:第\s*)?[0-9０-９]+(?:\s*(?:-|ー|－|の)\s*[0-9０-９]+)?\s*(?:号証|号)?)/);
    if (!match) {
        return null;
    }
    return normalizeEvidenceNumber(match[1]);
}
function extractDateCandidates(relativePath, text) {
    const searchText = `${relativePath}\n${text.slice(0, 4000)}`;
    const patterns = [
        /\b\d{4}[\/.-]\d{1,2}[\/.-]\d{1,2}\b/g,
        /\b\d{4}年\s*\d{1,2}月\s*\d{1,2}日/g,
        /(?:令和|平成|昭和)\s*\d{1,2}年\s*\d{1,2}月\s*\d{1,2}日/g,
    ];
    const candidates = [];
    for (const pattern of patterns) {
        for (const match of searchText.matchAll(pattern)) {
            candidates.push(match[0]);
        }
    }
    return (0, utils_1.uniqueLimited)(candidates, constants_1.MAX_DATE_CANDIDATES);
}
function inferDocumentKind(relativePath, text) {
    const searchText = `${relativePath}\n${text.slice(0, 1200)}`;
    const patterns = [
        ['訴状', /訴状/],
        ['答弁書', /答弁書/],
        ['準備書面', /準備書面/],
        ['証拠説明書', /証拠説明書|証拠目録/],
        ['反訳書', /反訳書|反訳|文字起こし/],
        ['告訴状', /告訴状/],
        ['送付書', /送付書/],
        ['期日請書', /期日請書/],
        ['控訴理由書', /控訴理由書/],
        ['控訴状', /控訴状/],
        ['上告理由書', /上告理由書/],
        ['上告状', /上告状|上告受理申立/],
        ['移送申立書', /移送申立/],
        ['忌避申立書', /忌避申立/],
        ['行政手続書面', /開示請求|審査請求|反論書/],
        ['メモ', /メモ|memo|note/i],
    ];
    for (const [kind, pattern] of patterns) {
        if (pattern.test(searchText)) {
            return kind;
        }
    }
    if (extractEvidenceNumber(relativePath, text)) {
        return '証拠資料';
    }
    return (0, utils_1.getPathExtname)(relativePath).toLowerCase() === '.md' ? 'Markdown資料' : 'テキスト資料';
}
function buildFileWarnings(relativePath, content, text) {
    const warnings = [];
    const trimmedText = text.trim();
    if (content.length === 0 || trimmedText.length === 0) {
        warnings.push('空ファイル、または本文が空白のみです。AI が内容を把握できません。');
    }
    else if (trimmedText.length < constants_1.VERY_SHORT_TEXT_CHARS) {
        warnings.push('本文が非常に短いため、OCR漏れや未完成ファイルの可能性があります。');
    }
    if (content.length > constants_1.LARGE_TEXT_FILE_BYTES) {
        warnings.push('長大なテキストです。AI が一度に読み切れない場合は、このファイルを分割して確認してください。');
    }
    if (text.includes('\uFFFD')) {
        warnings.push('文字化けの可能性があります。UTF-8として読めない文字が含まれているようです。');
    }
    if ((0, utils_1.getPathBasename)(relativePath).trim().length === 0) {
        warnings.push('ファイル名が空白に見えます。参照時に取り違えないよう注意してください。');
    }
    return warnings;
}

},
"src/lib/ai_archive/instruction_structure_renderer": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildInstructionStructure = buildInstructionStructure;
const utils_1 = require("./utils");
/**
 * README に載せる `instructions/` のツリー表示を生成する。
 * いったんオブジェクトの木にしてから描画することで、階層が増えても表示を崩さずに済む。
 */
function buildInstructionStructure(instructionEntries) {
    if (instructionEntries.length === 0) {
        return "";
    }
    // 例: { "行政": { "開示請求.md": null }, "sample.md": null } のような木を作る。
    const tree = {};
    for (const entry of instructionEntries) {
        const relativePath = entry.displayPath.replace(/^instructions\//, '');
        const parts = relativePath.split('/');
        let currentNode = tree;
        for (let i = 0; i < parts.length; i++) {
            const part = parts[i];
            const isLastPart = i === parts.length - 1;
            if (isLastPart) {
                currentNode[part] = null;
            }
            else {
                currentNode[part] = currentNode[part] || {};
                currentNode = currentNode[part];
            }
        }
    }
    // ディレクトリは 📁、ファイルは 📄 として、AI と人間のどちらにも読みやすい目次にする。
    function renderTree(node, indent = "  ") {
        let structure = "";
        const entries = Object.keys(node).sort((a, b) => {
            const aIsDirectory = node[a] !== null;
            const bIsDirectory = node[b] !== null;
            if (aIsDirectory && !bIsDirectory)
                return -1;
            if (!aIsDirectory && bIsDirectory)
                return 1;
            return (0, utils_1.compareInstructionNames)(a, b);
        });
        for (const entryName of entries) {
            const childNode = node[entryName];
            if (childNode === null) {
                structure += `${indent}📄 ${entryName}\n`;
            }
            else {
                structure += `${indent}📁 ${entryName}/\n`;
                structure += renderTree(childNode, indent + "  ");
            }
        }
        return structure;
    }
    return `📁 instructions/\n${renderTree(tree)}`;
}

},
"src/lib/ai_archive/manifest": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildArchiveManifest = buildArchiveManifest;
function buildArchiveManifest(caseName, scan, instructionEntries) {
    return {
        schemaVersion: 1,
        archiveType: 'houhi-ai-case-archive',
        generatedAt: new Date().toISOString(),
        caseName,
        roots: {
            caseDocuments: `${scan.caseRoot}/`,
            draftingInstructions: instructionEntries.length > 0 ? 'instructions/' : null,
        },
        entrypoints: [
            'START_HERE.md',
            'CASE_INDEX.md',
            'README.md',
            ...(scan.warnings.length > 0 ? ['WARNINGS.md'] : []),
        ],
        counts: {
            caseFiles: scan.caseFiles.length,
            instructionFiles: instructionEntries.length,
            skippedFiles: scan.skippedFiles.length,
            warnings: scan.warnings.length,
        },
        files: scan.caseFiles.map(file => ({
            path: file.displayPath,
            sourceRelativePath: file.relativePath,
            role: 'case_document',
            documentKind: file.documentKind,
            evidenceNumber: file.evidenceNumber,
            dateCandidates: file.dateCandidates,
            extension: file.extension,
            sizeBytes: file.sizeBytes,
            characterCount: file.characterCount,
            lineCount: file.lineCount,
            warnings: file.warnings,
        })),
        instructions: instructionEntries.map(entry => ({
            path: entry.displayPath,
            role: entry.isWorkflowGuide
                ? 'drafting_workflow_guide'
                : entry.isCommonRules
                    ? 'common_drafting_rules'
                    : 'drafting_instruction',
            sizeBytes: entry.content.length,
        })),
        skippedFiles: scan.skippedFiles,
        warnings: scan.warnings,
    };
}

},
"src/lib/ai_archive/readme_renderer": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildArchiveReadme = buildArchiveReadme;
const constants_1 = require("./constants");
const instruction_structure_renderer_1 = require("./instruction_structure_renderer");
function indentStructure(structure, indent = "  ") {
    if (structure.length === 0) {
        return "";
    }
    return structure
        .split('\n')
        .filter(line => line.length > 0)
        .map(line => `${indent}${line}`)
        .join('\n') + '\n';
}
/**
 * ZIP ルートに置く README を生成する。
 * AI が「事件資料」と「起案用指示書」を取り違えないよう、役割を明示している。
 */
function buildArchiveReadme(dirName, structure, instructionEntries, scan) {
    const hasInstructions = instructionEntries.length > 0;
    const instructionsStructure = (0, instruction_structure_renderer_1.buildInstructionStructure)(instructionEntries);
    const caseRoot = scan?.caseRoot || constants_1.CASE_DOCUMENTS_ROOT;
    const directoryStructure = `📁 ${caseRoot}/\n${indentStructure(structure)}${instructionsStructure}`;
    const warningLine = scan && scan.warnings.length > 0
        ? `- **\`WARNINGS.md\`** — Notes about empty, very large, skipped, or otherwise risky files.\n`
        : '';
    let readmeContent = `# Project Archive for AI Analysis

This archive is prepared so an AI can understand the case materials before answering questions or drafting documents.

- **\`START_HERE.md\`** — Read this first. It explains how to use this archive safely.
- **\`CASE_INDEX.md\`** — Human-readable index of case files, suggested reading order, evidence numbers, dates, and warnings.
- **\`manifest.json\`** — Machine-readable index for tools and AI systems.
${warningLine}- **\`${caseRoot}/\`** — The user's actual case documents from the original folder \`${dirName}\` (briefs, evidence lists, transcripts, etc.).
  These are the files you should read, analyze, and use as source material.
`;
    if (hasInstructions) {
        readmeContent += `- **\`instructions/\`** — Bundled drafting instructions.
  You may use these files as reference material when preparing court documents. Follow the matching instruction file for structure, formatting, and standard phrasing.
`;
    }
    readmeContent += `
## Directory Structure

\`\`\`
${directoryStructure}\`\`\`
`;
    if (hasInstructions) {
        const instructionList = instructionEntries
            .map(entry => {
            const description = entry.isWorkflowGuide
                ? 'Conversation flow for selecting a document type and collecting required facts.'
                : entry.isCommonRules
                    ? 'Common Markdown rules for all document types.'
                    : 'Reference instruction for the corresponding document type.';
            return `- \`${entry.displayPath}\` — ${description}`;
        })
            .join('\n');
        const hasCommonRules = instructionEntries.some(entry => entry.isCommonRules);
        const workflowGuide = instructionEntries.find(entry => entry.isWorkflowGuide);
        readmeContent += `
## Drafting Instructions

The files in \`instructions/\` are included so they can be used as reference material when drafting court documents.
Use the materials in \`${caseRoot}/\` for the facts of this case, and use the matching files in \`instructions/\` for writing guidance.

${workflowGuide ? `When the user has not yet chosen a filing type, start with \`${workflowGuide.displayPath}\`.\n` : ''}${hasCommonRules ? 'Start with `instructions/sample.md`, then use the document-type instruction that best matches the filing you want to prepare.\n\n' : ''}Available instruction files:
${instructionList}
`;
    }
    readmeContent += `
---
Generated by Saiban System Archive Tool
`;
    return readmeContent;
}

},
"src/lib/ai_archive/renderers": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildWarningsMarkdown = exports.buildStartHere = exports.buildArchiveReadme = exports.buildInstructionStructure = exports.buildCaseIndex = void 0;
var case_index_renderer_1 = require("./case_index_renderer");
Object.defineProperty(exports, "buildCaseIndex", { enumerable: true, get: function () { return case_index_renderer_1.buildCaseIndex; } });
var instruction_structure_renderer_1 = require("./instruction_structure_renderer");
Object.defineProperty(exports, "buildInstructionStructure", { enumerable: true, get: function () { return instruction_structure_renderer_1.buildInstructionStructure; } });
var readme_renderer_1 = require("./readme_renderer");
Object.defineProperty(exports, "buildArchiveReadme", { enumerable: true, get: function () { return readme_renderer_1.buildArchiveReadme; } });
var start_here_renderer_1 = require("./start_here_renderer");
Object.defineProperty(exports, "buildStartHere", { enumerable: true, get: function () { return start_here_renderer_1.buildStartHere; } });
var warnings_renderer_1 = require("./warnings_renderer");
Object.defineProperty(exports, "buildWarningsMarkdown", { enumerable: true, get: function () { return warnings_renderer_1.buildWarningsMarkdown; } });

},
"src/lib/ai_archive/start_here_renderer": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildStartHere = buildStartHere;
function buildStartHere(caseName, scan, instructionEntries) {
    const hasInstructions = instructionEntries.length > 0;
    const warningLine = scan.warnings.length > 0
        ? '- `WARNINGS.md` がある場合は、空ファイル・長大ファイル・除外ファイルなどの注意点を先に確認してください。'
        : '- このアーカイブには、読み込み前に確認すべき警告は検出されていません。';
    return `# START_HERE - AIへの読み込み指示

このZIPは、ChatGPTなどのAIが事件資料を読み込み、状況把握・質問回答・書面起案補助を行いやすいように整理したアーカイブです。

## 最初に読む順番

1. \`START_HERE.md\` - このファイルです。アーカイブの読み方を確認してください。
2. \`CASE_INDEX.md\` - 事件資料の一覧、推奨読解順、証拠番号や日付候補を確認してください。
3. \`manifest.json\` - 機械可読の索引です。必要に応じてファイル一覧や警告を確認してください。
4. \`${scan.caseRoot}/\` - 事件の事実関係を示す本文資料です。
${hasInstructions ? `5. \`instructions/\` - 書面を起案するときの形式・文体・Markdownルールです。事件の事実そのものではありません。` : ''}

## ユーザーから具体的な指示がない場合

このZIPだけがアップロードされ、ユーザーから「何をしてほしいか」の明確な指示がない場合は、いきなり書面を作り始めないでください。
まず \`CASE_INDEX.md\` と必要な範囲の \`${scan.caseRoot}/\` を読み、次の流れで応答してください。

1. 自己紹介し、このアーカイブを読んで事件資料の整理・質問回答・書面起案補助ができることを伝えてください。
2. 現在読み取れる状況を、根拠ファイルのパス付きで3〜6項目に要約してください。
3. 次に取れる手を、ユーザーが選びやすい形で提示してください。
4. 最後に「どれを進めますか」「何を作成・整理しますか」と聞き返してください。

提示する次の手の例:
- 事件の時系列を整理する
- 争点・主張・反論を整理する
- 証拠と証明したい事実の対応表を作る
- 不足資料・確認事項を洗い出す
- 準備書面、訴状、答弁書、控訴理由書などのMarkdown原案を作る
- 相手方主張への反論案を作る
- 裁判所や相手方に提出する短い連絡文・上申書案を作る

## ユーザーから具体的な指示がある場合

ユーザーが「訴状を起案して」「時系列を作って」「準備書面を起案して」「この証拠を評価して」など具体的に依頼している場合は、その依頼を優先してください。
ただし、必要な情報が不足しているときは、推測で完成させず、不足点を具体的に質問してください。

## 重要な区別

- \`${scan.caseRoot}/\` は、ユーザーが渡した事件資料です。事実認定、経過整理、証拠確認、質問回答ではこのフォルダを主な根拠にしてください。
${hasInstructions ? '- `instructions/` は、起案時の書式・構成・定型表現の参照資料です。ここに書かれた内容を事件の事実として扱わないでください。' : ''}
- 回答では、可能な限り根拠ファイルのパスを示してください。例: \`${scan.caseRoot}/訴状.md\`
- 不明な点、資料から読み取れない点、推測が混じる点は、断定せずに質問または留保してください。
- 事実、推測、法的評価、起案上の提案は分けて説明してください。
${warningLine}

## アーカイブ概要

- 元フォルダ名: \`${caseName}\`
- 事件資料ファイル数: ${scan.caseFiles.length}
- 起案指示書ファイル数: ${instructionEntries.length}
- ZIPに含めなかった非対象ファイル数: ${scan.skippedFiles.length}
- 警告・注意点: ${scan.warnings.length}

`;
}

},
"src/lib/ai_archive/utils": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isTargetTextFile = isTargetTextFile;
exports.compareInstructionNames = compareInstructionNames;
exports.compareInstructionPaths = compareInstructionPaths;
exports.normalizeArchivePath = normalizeArchivePath;
exports.getPathBasename = getPathBasename;
exports.getPathExtname = getPathExtname;
exports.getUtf8Text = getUtf8Text;
exports.countLines = countLines;
exports.uniqueLimited = uniqueLimited;
exports.formatBytes = formatBytes;
exports.escapeMarkdownTableCell = escapeMarkdownTableCell;
/**
 * AI に渡す資料として収録する対象ファイルか判定する。
 * 画像や PDF などの重いバイナリは除外し、本文を直接読める Markdown / text に限定する。
 */
function isTargetTextFile(filePath) {
    const ext = getPathExtname(filePath).toLowerCase();
    return ext === '.md' || ext === '.txt';
}
/**
 * 指示書や資料名を並べるための比較関数。
 * `sample.md` は共通ルールなので、常に先頭に出して AI が最初に参照しやすくする。
 */
function compareInstructionNames(a, b) {
    if (a === 'sample.md')
        return -1;
    if (b === 'sample.md')
        return 1;
    return a.localeCompare(b, 'ja');
}
/**
 * `dir/file.md` のようなパスを階層ごとに比較する。
 * 単純な文字列比較だと親子関係や `sample.md` の優先順位が崩れやすいため、
 * パスを `/` で分解して、各階層で同じ並び規則を適用する。
 */
function compareInstructionPaths(a, b) {
    const aParts = a.split('/');
    const bParts = b.split('/');
    const maxLength = Math.max(aParts.length, bParts.length);
    for (let i = 0; i < maxLength; i++) {
        const aPart = aParts[i];
        const bPart = bParts[i];
        if (aPart == null)
            return -1;
        if (bPart == null)
            return 1;
        if (aPart === bPart)
            continue;
        return compareInstructionNames(aPart, bPart);
    }
    return 0;
}
function normalizeArchivePath(filePath) {
    return filePath.replace(/\\/g, '/');
}
function getPathBasename(filePath) {
    const normalizedPath = normalizeArchivePath(filePath);
    const parts = normalizedPath.split('/').filter(part => part.length > 0);
    return parts[parts.length - 1] || '';
}
function getPathExtname(filePath) {
    const basename = getPathBasename(filePath);
    const dotIndex = basename.lastIndexOf('.');
    if (dotIndex <= 0) {
        return '';
    }
    return basename.slice(dotIndex);
}
function getUtf8Text(content) {
    return content.toString('utf-8');
}
function countLines(text) {
    if (text.length === 0) {
        return 0;
    }
    return text.split(/\r\n|\r|\n/).length;
}
function uniqueLimited(values, limit) {
    const result = [];
    const seen = new Set();
    for (const value of values) {
        const normalizedValue = value.replace(/\s+/g, '');
        if (seen.has(normalizedValue))
            continue;
        seen.add(normalizedValue);
        result.push(value.trim());
        if (result.length >= limit)
            break;
    }
    return result;
}
function formatBytes(sizeBytes) {
    if (sizeBytes < 1024) {
        return `${sizeBytes} B`;
    }
    if (sizeBytes < 1024 * 1024) {
        return `${(sizeBytes / 1024).toFixed(1)} KB`;
    }
    return `${(sizeBytes / 1024 / 1024).toFixed(1)} MB`;
}
function escapeMarkdownTableCell(value) {
    if (value == null || value === '') {
        return '-';
    }
    return String(value).replace(/\|/g, '\\|').replace(/\r?\n/g, '<br>');
}

},
"src/lib/ai_archive/warnings_renderer": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildWarningsMarkdown = buildWarningsMarkdown;
const utils_1 = require("./utils");
function buildWarningsMarkdown(warnings) {
    if (warnings.length === 0) {
        return '';
    }
    const rows = warnings
        .map(warning => `| ${(0, utils_1.escapeMarkdownTableCell)(warning.severity)} | \`${(0, utils_1.escapeMarkdownTableCell)(warning.path)}\` | ${(0, utils_1.escapeMarkdownTableCell)(warning.message)} |`)
        .join('\n');
    return `# WARNINGS - AI読み込み時の注意

以下は、AIがアーカイブを読むときに注意すべき点です。警告があるファイルは、内容の欠落、文字化け、長大化、または参照時の取り違えに注意してください。

| 種別 | パス | 内容 |
| --- | --- | --- |
${rows}
`;
}

},
"src/web/zip": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildStoredZip = buildStoredZip;
const crcTable = (() => {
    const table = new Uint32Array(256);
    for (let i = 0; i < table.length; i++) {
        let value = i;
        for (let bit = 0; bit < 8; bit++) {
            value = value & 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1;
        }
        table[i] = value >>> 0;
    }
    return table;
})();
function crc32(data) {
    let crc = 0xffffffff;
    for (const byte of data) {
        crc = crcTable[(crc ^ byte) & 0xff] ^ (crc >>> 8);
    }
    return (crc ^ 0xffffffff) >>> 0;
}
function getDosDateTime(date) {
    const year = Math.max(1980, Math.min(2107, date.getFullYear()));
    const dosTime = (date.getHours() << 11) | (date.getMinutes() << 5) | Math.floor(date.getSeconds() / 2);
    const dosDate = ((year - 1980) << 9) | ((date.getMonth() + 1) << 5) | date.getDate();
    return { dosTime, dosDate };
}
function writeUint16(view, offset, value) {
    view.setUint16(offset, value, true);
}
function writeUint32(view, offset, value) {
    view.setUint32(offset, value >>> 0, true);
}
function concat(parts) {
    const totalLength = parts.reduce((sum, part) => sum + part.length, 0);
    const output = new Uint8Array(totalLength);
    let offset = 0;
    for (const part of parts) {
        output.set(part, offset);
        offset += part.length;
    }
    return output;
}
function makeLocalHeader(entry) {
    const header = new Uint8Array(30 + entry.pathBytes.length);
    const view = new DataView(header.buffer);
    writeUint32(view, 0, 0x04034b50);
    writeUint16(view, 4, 20);
    writeUint16(view, 6, 0x0800);
    writeUint16(view, 8, 0);
    writeUint16(view, 10, entry.dosTime);
    writeUint16(view, 12, entry.dosDate);
    writeUint32(view, 14, entry.crc32);
    writeUint32(view, 18, entry.size);
    writeUint32(view, 22, entry.size);
    writeUint16(view, 26, entry.pathBytes.length);
    writeUint16(view, 28, 0);
    header.set(entry.pathBytes, 30);
    return header;
}
function makeCentralHeader(entry) {
    const header = new Uint8Array(46 + entry.pathBytes.length);
    const view = new DataView(header.buffer);
    writeUint32(view, 0, 0x02014b50);
    writeUint16(view, 4, 20);
    writeUint16(view, 6, 20);
    writeUint16(view, 8, 0x0800);
    writeUint16(view, 10, 0);
    writeUint16(view, 12, entry.dosTime);
    writeUint16(view, 14, entry.dosDate);
    writeUint32(view, 16, entry.crc32);
    writeUint32(view, 20, entry.size);
    writeUint32(view, 24, entry.size);
    writeUint16(view, 28, entry.pathBytes.length);
    writeUint16(view, 30, 0);
    writeUint16(view, 32, 0);
    writeUint16(view, 34, 0);
    writeUint16(view, 36, 0);
    writeUint32(view, 38, 0);
    writeUint32(view, 42, entry.offset);
    header.set(entry.pathBytes, 46);
    return header;
}
function makeEndRecord(entryCount, centralDirectorySize, centralDirectoryOffset) {
    const record = new Uint8Array(22);
    const view = new DataView(record.buffer);
    writeUint32(view, 0, 0x06054b50);
    writeUint16(view, 4, 0);
    writeUint16(view, 6, 0);
    writeUint16(view, 8, entryCount);
    writeUint16(view, 10, entryCount);
    writeUint32(view, 12, centralDirectorySize);
    writeUint32(view, 16, centralDirectoryOffset);
    writeUint16(view, 20, 0);
    return record;
}
function buildStoredZip(entries) {
    const encoder = new TextEncoder();
    const now = new Date();
    const { dosTime, dosDate } = getDosDateTime(now);
    const fileParts = [];
    const centralEntries = [];
    let offset = 0;
    for (const input of entries) {
        const pathBytes = encoder.encode(input.path);
        const entry = {
            pathBytes,
            crc32: crc32(input.data),
            size: input.data.length,
            offset,
            dosTime,
            dosDate,
        };
        const header = makeLocalHeader(entry);
        fileParts.push(header, input.data);
        centralEntries.push(entry);
        offset += header.length + input.data.length;
    }
    const centralOffset = offset;
    const centralParts = centralEntries.map(makeCentralHeader);
    const centralSize = centralParts.reduce((sum, part) => sum + part.length, 0);
    const endRecord = makeEndRecord(entries.length, centralSize, centralOffset);
    return concat([...fileParts, ...centralParts, endRecord]);
}

},
"src/web/archive": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const constants_1 = require("../lib/ai_archive/constants");
const inference_1 = require("../lib/ai_archive/inference");
const manifest_1 = require("../lib/ai_archive/manifest");
const renderers_1 = require("../lib/ai_archive/renderers");
const utils_1 = require("../lib/ai_archive/utils");
const zip_1 = require("./zip");
const archiveData = window.HOUHI_ARCHIVE_DATA;
const encoder = new TextEncoder();
const directoryInput = document.getElementById('directoryInput');
const fileInput = document.getElementById('archiveFileInput');
const dropZone = document.getElementById('archiveDropZone');
const chooseDirectoryButton = document.getElementById('chooseDirectoryButton');
const chooseFilesButton = document.getElementById('chooseFilesButton');
const createArchiveButton = document.getElementById('createArchiveButton');
const copyArchiveGuideButton = document.getElementById('copyArchiveGuideButton');
const archiveStatus = document.getElementById('archiveStatus');
const fileSummary = document.getElementById('fileSummary');
const archiveGuideOutput = document.getElementById('archiveGuideOutput');
const archiveLinks = document.getElementById('archiveLinks');
let selectedFiles = [];
let latestGuide = '';
function setStatus(message) {
    archiveStatus.textContent = message;
}
function setLinksVisible(visible) {
    archiveLinks.hidden = !visible;
}
function sanitizePath(value) {
    const normalized = value
        .replace(/\\/g, '/')
        .replace(/^[a-zA-Z]:\//, '')
        .replace(/^\/+/, '');
    const parts = normalized
        .split('/')
        .map(part => part.trim())
        .filter(part => part.length > 0 && part !== '.' && part !== '..');
    return parts.join('/');
}
function getInputRelativePath(file, fallbackIndex) {
    const relativePath = sanitizePath(file.webkitRelativePath || file.name);
    return relativePath || `file-${fallbackIndex + 1}.txt`;
}
function getCommonRoot(paths) {
    if (paths.length === 0) {
        return null;
    }
    const firstParts = paths[0].split('/');
    if (firstParts.length < 2) {
        return null;
    }
    const root = firstParts[0];
    const allHaveRoot = paths.every(path => {
        const parts = path.split('/');
        return parts.length >= 2 && parts[0] === root;
    });
    return allHaveRoot ? root : null;
}
function prepareFiles(files) {
    const sanitized = files.map((entry, index) => ({
        file: entry.file,
        relativePath: sanitizePath(entry.relativePath) || getInputRelativePath(entry.file, index),
    }));
    const commonRoot = getCommonRoot(sanitized.map(entry => entry.relativePath));
    const prepared = sanitized.map(entry => {
        const relativePath = commonRoot
            ? entry.relativePath.slice(commonRoot.length + 1)
            : entry.relativePath;
        return {
            file: entry.file,
            relativePath: relativePath || getInputRelativePath(entry.file, 0),
        };
    });
    return {
        caseName: commonRoot || 'ai-archive',
        files: prepared,
    };
}
function getSelectedFileStats(files) {
    const prepared = prepareFiles(files).files;
    return {
        targetCount: prepared.filter(entry => (0, utils_1.isTargetTextFile)(entry.relativePath)).length,
        skippedCount: prepared.filter(entry => !(0, utils_1.isTargetTextFile)(entry.relativePath)).length,
    };
}
function updateSelectedFiles(files) {
    selectedFiles = files.sort((a, b) => (0, utils_1.compareInstructionPaths)(a.relativePath, b.relativePath));
    const stats = getSelectedFileStats(selectedFiles);
    fileSummary.textContent = selectedFiles.length === 0
        ? '.md / .txt を含むフォルダまたはファイルを選択してください。'
        : `${selectedFiles.length}件を選択中。収録対象 ${stats.targetCount}件、除外 ${stats.skippedCount}件。`;
    createArchiveButton.disabled = stats.targetCount === 0;
    setStatus(stats.targetCount === 0 ? '対象ファイルなし' : '作成できます');
    setLinksVisible(false);
}
function makeArchiveWarning(caseFiles, skippedFiles) {
    const warnings = [];
    for (const file of caseFiles) {
        for (const message of file.warnings) {
            warnings.push({
                path: file.displayPath,
                severity: 'warning',
                message,
            });
        }
    }
    const filesByBasename = new Map();
    for (const file of caseFiles) {
        const basename = (0, utils_1.getPathBasename)(file.relativePath).toLowerCase();
        const group = filesByBasename.get(basename) || [];
        group.push(file);
        filesByBasename.set(basename, group);
    }
    for (const files of filesByBasename.values()) {
        if (files.length <= 1)
            continue;
        warnings.push({
            path: files.map(file => file.displayPath).join(', '),
            severity: 'info',
            message: '同じファイル名の資料が複数あります。AI に参照させるときはパス全体で区別してください。',
        });
    }
    if (skippedFiles.length > 0) {
        const examples = skippedFiles
            .slice(0, constants_1.MAX_SKIPPED_FILES_IN_WARNING)
            .map(file => file.relativePath)
            .join(', ');
        const suffix = skippedFiles.length > constants_1.MAX_SKIPPED_FILES_IN_WARNING
            ? ` ほか ${skippedFiles.length - constants_1.MAX_SKIPPED_FILES_IN_WARNING} 件`
            : '';
        warnings.push({
            path: '(archive)',
            severity: 'info',
            message: `.md / .txt 以外のファイル ${skippedFiles.length} 件はZIPに含めていません: ${examples}${suffix}`,
        });
    }
    return warnings;
}
function addTreeNode(tree, relativePath) {
    const parts = relativePath.split('/').filter(Boolean);
    let node = tree;
    for (let i = 0; i < parts.length; i++) {
        const part = parts[i];
        const isLast = i === parts.length - 1;
        if (isLast) {
            node[part] = null;
        }
        else {
            node[part] = node[part] || {};
            node = node[part];
        }
    }
}
function renderTree(node, indent = '') {
    const names = Object.keys(node).sort(utils_1.compareInstructionPaths);
    let output = '';
    for (const name of names) {
        const child = node[name];
        if (child === null) {
            output += `${indent}📄 ${name}\n`;
        }
        else {
            output += `${indent}📁 ${name}/\n`;
            output += renderTree(child, `${indent}  `);
        }
    }
    return output;
}
function buildDirectoryStructure(caseFiles) {
    const tree = {};
    for (const file of caseFiles) {
        addTreeNode(tree, file.relativePath);
    }
    return renderTree(tree);
}
async function buildScan(preparedFiles) {
    const caseFiles = [];
    const skippedFiles = [];
    for (const entry of preparedFiles) {
        const relativePath = sanitizePath(entry.relativePath);
        if (!(0, utils_1.isTargetTextFile)(relativePath)) {
            skippedFiles.push({
                relativePath,
                extension: (0, utils_1.getPathExtname)(relativePath).toLowerCase(),
                sizeBytes: entry.file.size,
                reason: '.md / .txt 以外のファイルはAIアーカイブの本文資料から除外します。',
            });
            continue;
        }
        const text = await entry.file.text();
        const content = encoder.encode(text);
        const archivePath = `${constants_1.CASE_DOCUMENTS_ROOT}/${relativePath}`;
        caseFiles.push({
            relativePath,
            archivePath,
            displayPath: archivePath,
            content: content,
            extension: (0, utils_1.getPathExtname)(relativePath).toLowerCase(),
            sizeBytes: content.length,
            characterCount: text.length,
            lineCount: (0, utils_1.countLines)(text),
            documentKind: (0, inference_1.inferDocumentKind)(relativePath, text),
            evidenceNumber: (0, inference_1.extractEvidenceNumber)(relativePath, text),
            dateCandidates: (0, inference_1.extractDateCandidates)(relativePath, text),
            warnings: (0, inference_1.buildFileWarnings)(relativePath, content, text),
        });
    }
    caseFiles.sort((a, b) => (0, utils_1.compareInstructionPaths)(a.relativePath, b.relativePath));
    skippedFiles.sort((a, b) => (0, utils_1.compareInstructionPaths)(a.relativePath, b.relativePath));
    return {
        caseRoot: constants_1.CASE_DOCUMENTS_ROOT,
        caseFiles,
        skippedFiles,
        warnings: makeArchiveWarning(caseFiles, skippedFiles),
    };
}
function buildInstructionEntries() {
    return archiveData.instructions.map(entry => ({
        archivePath: entry.displayPath,
        displayPath: entry.displayPath,
        content: encoder.encode(entry.content),
        isCommonRules: entry.isCommonRules,
        isWorkflowGuide: entry.isWorkflowGuide,
    }));
}
function ensureUniqueEntries(entries) {
    const seen = new Map();
    return entries.map(entry => {
        const count = seen.get(entry.path) || 0;
        seen.set(entry.path, count + 1);
        if (count === 0) {
            return entry;
        }
        const dotIndex = entry.path.lastIndexOf('.');
        const uniquePath = dotIndex > 0
            ? `${entry.path.slice(0, dotIndex)}-${count + 1}${entry.path.slice(dotIndex)}`
            : `${entry.path}-${count + 1}`;
        return { ...entry, path: uniquePath };
    });
}
function buildUploadGuide(zipName) {
    return `添付したAIアーカイブZIP（${zipName}）を読み込み、まず START_HERE.md と CASE_INDEX.md を確認してください。このメッセージで「訴状を起案して」「時系列を作って」などの具体的な依頼がある場合は、その依頼を優先してください。具体的な依頼がまだない場合は、現在読み取れる状況を根拠ファイルのパス付きで要約し、次に取れる手を提案したうえで、何をしてほしいか私に質問してください。`;
}
function downloadZip(zipName, bytes) {
    const arrayBuffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
    const blob = new Blob([arrayBuffer], { type: 'application/zip' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = zipName;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
}
async function createArchive() {
    if (selectedFiles.length === 0) {
        return;
    }
    createArchiveButton.disabled = true;
    copyArchiveGuideButton.disabled = true;
    setStatus('作成中...');
    setLinksVisible(false);
    try {
        const prepared = prepareFiles(selectedFiles);
        const scan = await buildScan(prepared.files);
        if (scan.caseFiles.length === 0) {
            setStatus('対象ファイルなし');
            return;
        }
        const instructionEntries = buildInstructionEntries();
        const structure = buildDirectoryStructure(scan.caseFiles);
        const caseName = prepared.caseName || 'ai-archive';
        const zipName = `${caseName}.zip`;
        const entries = [
            ...scan.caseFiles.map(file => ({
                path: file.archivePath,
                data: file.content,
            })),
            ...instructionEntries.map(entry => ({
                path: entry.archivePath,
                data: entry.content,
            })),
            {
                path: 'START_HERE.md',
                data: encoder.encode((0, renderers_1.buildStartHere)(caseName, scan, instructionEntries)),
            },
            {
                path: 'CASE_INDEX.md',
                data: encoder.encode((0, renderers_1.buildCaseIndex)(caseName, scan)),
            },
            {
                path: 'manifest.json',
                data: encoder.encode(JSON.stringify((0, manifest_1.buildArchiveManifest)(caseName, scan, instructionEntries), null, 2)),
            },
            {
                path: 'README.md',
                data: encoder.encode((0, renderers_1.buildArchiveReadme)(caseName, structure, instructionEntries, scan)),
            },
        ];
        if (scan.warnings.length > 0) {
            entries.push({
                path: 'WARNINGS.md',
                data: encoder.encode((0, renderers_1.buildWarningsMarkdown)(scan.warnings)),
            });
        }
        const zipBytes = (0, zip_1.buildStoredZip)(ensureUniqueEntries(entries));
        downloadZip(zipName, zipBytes);
        latestGuide = buildUploadGuide(zipName);
        archiveGuideOutput.value = latestGuide;
        copyArchiveGuideButton.disabled = false;
        setStatus(`作成しました。収録 ${scan.caseFiles.length}件、除外 ${scan.skippedFiles.length}件。`);
        setLinksVisible(true);
    }
    catch (err) {
        console.error(err);
        setStatus('作成に失敗しました。ファイルを確認してください。');
    }
    finally {
        const stats = getSelectedFileStats(selectedFiles);
        createArchiveButton.disabled = stats.targetCount === 0;
    }
}
async function copyGuide() {
    if (!latestGuide) {
        archiveGuideOutput.select();
        latestGuide = archiveGuideOutput.value;
    }
    try {
        if (navigator.clipboard && window.isSecureContext) {
            await navigator.clipboard.writeText(latestGuide);
        }
        else {
            archiveGuideOutput.focus();
            archiveGuideOutput.select();
            document.execCommand('copy');
        }
        setStatus('指示文をコピーしました');
        setLinksVisible(true);
    }
    catch (err) {
        console.error(err);
        setStatus('コピーできませんでした。本文を選択してコピーしてください。');
    }
}
function filesFromInput(fileList) {
    return Array.from(fileList || []).map((file, index) => ({
        file,
        relativePath: getInputRelativePath(file, index),
    }));
}
function readDirectoryEntries(reader) {
    return new Promise((resolve, reject) => {
        const entries = [];
        function readBatch() {
            reader.readEntries(batch => {
                if (batch.length === 0) {
                    resolve(entries);
                    return;
                }
                entries.push(...batch);
                readBatch();
            }, reject);
        }
        readBatch();
    });
}
async function collectEntryFiles(entry) {
    if (entry.isFile) {
        const fileEntry = entry;
        const file = await new Promise((resolve, reject) => fileEntry.file(resolve, reject));
        return [{
                file,
                relativePath: sanitizePath(entry.fullPath || entry.name) || file.name,
            }];
    }
    if (entry.isDirectory) {
        const directoryEntry = entry;
        const children = await readDirectoryEntries(directoryEntry.createReader());
        const nested = await Promise.all(children.map(collectEntryFiles));
        return nested.flat();
    }
    return [];
}
async function filesFromDrop(dataTransfer) {
    const entries = Array.from(dataTransfer.items || [])
        .filter(item => item.kind === 'file')
        .map(item => {
        const getEntry = item.webkitGetAsEntry;
        return typeof getEntry === 'function' ? getEntry.call(item) : null;
    })
        .filter((entry) => entry != null);
    if (entries.length > 0) {
        const nested = await Promise.all(entries.map(collectEntryFiles));
        return nested.flat();
    }
    return filesFromInput(dataTransfer.files);
}
chooseDirectoryButton.addEventListener('click', () => directoryInput.click());
chooseFilesButton.addEventListener('click', () => fileInput.click());
createArchiveButton.addEventListener('click', createArchive);
copyArchiveGuideButton.addEventListener('click', copyGuide);
directoryInput.addEventListener('change', () => updateSelectedFiles(filesFromInput(directoryInput.files)));
fileInput.addEventListener('change', () => updateSelectedFiles(filesFromInput(fileInput.files)));
dropZone.addEventListener('click', () => directoryInput.click());
dropZone.addEventListener('dragover', event => {
    event.preventDefault();
    dropZone.classList.add('drag-over');
});
dropZone.addEventListener('dragleave', () => dropZone.classList.remove('drag-over'));
dropZone.addEventListener('drop', async (event) => {
    event.preventDefault();
    dropZone.classList.remove('drag-over');
    setStatus('読み込み中...');
    updateSelectedFiles(await filesFromDrop(event.dataTransfer));
});
archiveGuideOutput.value = 'ZIPを作成すると、Chat AIへ貼り付ける指示文がここに表示されます。';
createArchiveButton.disabled = true;
copyArchiveGuideButton.disabled = true;
setLinksVisible(false);
updateSelectedFiles([]);

}
  };
  var cache = {};
  function resolve(from, request) {
    if (request.charAt(0) !== '.') return request;
    var parts = from.split('/');
    parts.pop();
    var raw = parts.concat(request.split('/'));
    var out = [];
    for (var i = 0; i < raw.length; i++) {
      var part = raw[i];
      if (!part || part === '.') continue;
      if (part === '..') out.pop();
      else out.push(part);
    }
    return out.join('/').replace(/\.(js|ts)$/, '');
  }
  function load(id) {
    if (cache[id]) return cache[id].exports;
    if (!modules[id]) throw new Error('Module not found: ' + id);
    var module = { exports: {} };
    cache[id] = module;
    modules[id](function (request) { return load(resolve(id, request)); }, module, module.exports);
    return module.exports;
  }
  load("src/web/archive");
}());
