// Generated by scripts/build_web.js. Do not edit directly.
(function () {
  var modules = {
"src/web/zip": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.buildStoredZip = buildStoredZip;
const crcTable = (() => {
    const table = new Uint32Array(256);
    for (let i = 0; i < table.length; i++) {
        let value = i;
        for (let bit = 0; bit < 8; bit++) {
            value = value & 1 ? 0xedb88320 ^ (value >>> 1) : value >>> 1;
        }
        table[i] = value >>> 0;
    }
    return table;
})();
function crc32(data) {
    let crc = 0xffffffff;
    for (const byte of data) {
        crc = crcTable[(crc ^ byte) & 0xff] ^ (crc >>> 8);
    }
    return (crc ^ 0xffffffff) >>> 0;
}
function getDosDateTime(date) {
    const year = Math.max(1980, Math.min(2107, date.getFullYear()));
    const dosTime = (date.getHours() << 11) | (date.getMinutes() << 5) | Math.floor(date.getSeconds() / 2);
    const dosDate = ((year - 1980) << 9) | ((date.getMonth() + 1) << 5) | date.getDate();
    return { dosTime, dosDate };
}
function writeUint16(view, offset, value) {
    view.setUint16(offset, value, true);
}
function writeUint32(view, offset, value) {
    view.setUint32(offset, value >>> 0, true);
}
function concat(parts) {
    const totalLength = parts.reduce((sum, part) => sum + part.length, 0);
    const output = new Uint8Array(totalLength);
    let offset = 0;
    for (const part of parts) {
        output.set(part, offset);
        offset += part.length;
    }
    return output;
}
function makeLocalHeader(entry) {
    const header = new Uint8Array(30 + entry.pathBytes.length);
    const view = new DataView(header.buffer);
    writeUint32(view, 0, 0x04034b50);
    writeUint16(view, 4, 20);
    writeUint16(view, 6, 0x0800);
    writeUint16(view, 8, 0);
    writeUint16(view, 10, entry.dosTime);
    writeUint16(view, 12, entry.dosDate);
    writeUint32(view, 14, entry.crc32);
    writeUint32(view, 18, entry.size);
    writeUint32(view, 22, entry.size);
    writeUint16(view, 26, entry.pathBytes.length);
    writeUint16(view, 28, 0);
    header.set(entry.pathBytes, 30);
    return header;
}
function makeCentralHeader(entry) {
    const header = new Uint8Array(46 + entry.pathBytes.length);
    const view = new DataView(header.buffer);
    writeUint32(view, 0, 0x02014b50);
    writeUint16(view, 4, 20);
    writeUint16(view, 6, 20);
    writeUint16(view, 8, 0x0800);
    writeUint16(view, 10, 0);
    writeUint16(view, 12, entry.dosTime);
    writeUint16(view, 14, entry.dosDate);
    writeUint32(view, 16, entry.crc32);
    writeUint32(view, 20, entry.size);
    writeUint32(view, 24, entry.size);
    writeUint16(view, 28, entry.pathBytes.length);
    writeUint16(view, 30, 0);
    writeUint16(view, 32, 0);
    writeUint16(view, 34, 0);
    writeUint16(view, 36, 0);
    writeUint32(view, 38, 0);
    writeUint32(view, 42, entry.offset);
    header.set(entry.pathBytes, 46);
    return header;
}
function makeEndRecord(entryCount, centralDirectorySize, centralDirectoryOffset) {
    const record = new Uint8Array(22);
    const view = new DataView(record.buffer);
    writeUint32(view, 0, 0x06054b50);
    writeUint16(view, 4, 0);
    writeUint16(view, 6, 0);
    writeUint16(view, 8, entryCount);
    writeUint16(view, 10, entryCount);
    writeUint32(view, 12, centralDirectorySize);
    writeUint32(view, 16, centralDirectoryOffset);
    writeUint16(view, 20, 0);
    return record;
}
function buildStoredZip(entries) {
    const encoder = new TextEncoder();
    const now = new Date();
    const { dosTime, dosDate } = getDosDateTime(now);
    const fileParts = [];
    const centralEntries = [];
    let offset = 0;
    for (const input of entries) {
        const pathBytes = encoder.encode(input.path);
        const entry = {
            pathBytes,
            crc32: crc32(input.data),
            size: input.data.length,
            offset,
            dosTime,
            dosDate,
        };
        const header = makeLocalHeader(entry);
        fileParts.push(header, input.data);
        centralEntries.push(entry);
        offset += header.length + input.data.length;
    }
    const centralOffset = offset;
    const centralParts = centralEntries.map(makeCentralHeader);
    const centralSize = centralParts.reduce((sum, part) => sum + part.length, 0);
    const endRecord = makeEndRecord(entries.length, centralSize, centralOffset);
    return concat([...fileParts, ...centralParts, endRecord]);
}

},
"src/web/stamp": function(require, module, exports) {
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const zip_1 = require("./zip");
const DEFAULT_FONT_SIZE = 20;
const MARGIN_RIGHT = 15;
const MARGIN_TOP = 12;
const STAMP_OUTLINE = 1.5;
const STAMP_SUFFIX = '号証';
const A4_WIDTH = 595.28;
const A4_HEIGHT = 841.89;
const PAGE_SIZE_TOLERANCE = 0.5;
const IMAGE_MARGIN = 36;
const IMAGE_EXTENSIONS = ['.jpg', '.jpeg', '.png'];
const fileInput = document.getElementById('stampFileInput');
const dropZone = document.getElementById('stampDropZone');
const chooseFilesButton = document.getElementById('chooseStampFilesButton');
const stampButton = document.getElementById('stampButton');
const allPagesCheckbox = document.getElementById('stampAllPages');
const noBlankPagesCheckbox = document.getElementById('stampNoBlankPages');
const stampStatus = document.getElementById('stampStatus');
const stampSummary = document.getElementById('stampSummary');
const stampLog = document.getElementById('stampLog');
const stampProgress = document.getElementById('stampProgress');
const stampProgressText = document.getElementById('stampProgressText');
let selectedFiles = [];
function setStatus(message) {
    stampStatus.textContent = message;
}
function appendLog(message) {
    stampLog.value = stampLog.value ? `${stampLog.value}\n${message}` : message;
    stampLog.scrollTop = stampLog.scrollHeight;
}
function setProgress(done, total) {
    const safeTotal = Math.max(1, total);
    stampProgress.max = safeTotal;
    stampProgress.value = Math.min(done, safeTotal);
    stampProgressText.textContent = `${Math.round((stampProgress.value / safeTotal) * 100)}%`;
}
function toHalfWidthDigits(value) {
    return value.replace(/[０-９]/g, char => String.fromCharCode(char.charCodeAt(0) - 0xfee0));
}
function toHalfWidthAscii(value) {
    return value.replace(/[Ａ-Ｚａ-ｚ]/g, char => String.fromCharCode(char.charCodeAt(0) - 0xfee0));
}
function getBasename(filePath) {
    const normalized = filePath.replace(/\\/g, '/');
    const parts = normalized.split('/').filter(Boolean);
    return parts[parts.length - 1] || normalized;
}
function getExtname(filePath) {
    const basename = getBasename(filePath);
    const dotIndex = basename.lastIndexOf('.');
    if (dotIndex <= 0) {
        return '';
    }
    return basename.slice(dotIndex).toLowerCase();
}
function stripExtname(filePath) {
    const basename = getBasename(filePath);
    const dotIndex = basename.lastIndexOf('.');
    return dotIndex <= 0 ? basename : basename.slice(0, dotIndex);
}
function extractEvidenceNumber(filename) {
    const normalizedName = toHalfWidthAscii(toHalfWidthDigits(getBasename(filename))).replace(/[a-z]/g, char => char.toUpperCase());
    const match = normalizedName.match(/^([甲乙丙丁戊証疎][A-Z]?[0-9]+(?:[\-ー－の][0-9]+)?)/);
    if (!match) {
        return null;
    }
    return match[1].replace(/[ー－]/g, '-');
}
function naturalSortKey(filename) {
    const evidenceNumber = extractEvidenceNumber(filename);
    const match = evidenceNumber?.match(/[甲乙丙丁戊証疎]([A-Z]?)([0-9]+)(?:[\-の]([0-9]+))?/);
    if (!match) {
        return [Number.MAX_SAFE_INTEGER, Number.MAX_SAFE_INTEGER, Number.MAX_SAFE_INTEGER];
    }
    const letterRank = match[1] ? match[1].charCodeAt(0) - 64 : 0;
    return [letterRank, Number(match[2]), match[3] ? Number(match[3]) : 0];
}
function isImageFile(file) {
    return IMAGE_EXTENSIONS.includes(getExtname(file.name));
}
function isPdfFile(file) {
    return getExtname(file.name) === '.pdf' || file.type === 'application/pdf';
}
function isSupportedFile(file) {
    return isPdfFile(file) || isImageFile(file);
}
function getA4PrintScaleForPage(width, height) {
    const isLandscape = width > height;
    const [a4W, a4H] = isLandscape ? [A4_HEIGHT, A4_WIDTH] : [A4_WIDTH, A4_HEIGHT];
    return Math.min(a4W / width, a4H / height);
}
function getA4PageSizeForPage(width, height) {
    return width > height ? [A4_HEIGHT, A4_WIDTH] : [A4_WIDTH, A4_HEIGHT];
}
function isA4PageSize(width, height) {
    const [a4W, a4H] = getA4PageSizeForPage(width, height);
    return Math.abs(width - a4W) <= PAGE_SIZE_TOLERANCE
        && Math.abs(height - a4H) <= PAGE_SIZE_TOLERANCE;
}
function getA4Placement(width, height) {
    const [pageW, pageH] = getA4PageSizeForPage(width, height);
    const scale = Math.min(pageW / width, pageH / height, 1);
    const drawW = width * scale;
    const drawH = height * scale;
    return {
        pageW,
        pageH,
        x: (pageW - drawW) / 2,
        y: (pageH - drawH) / 2,
        width: drawW,
        height: drawH,
    };
}
function pageHasContents(page) {
    return Boolean(page?.node && typeof page.node.Contents === 'function' && page.node.Contents());
}
function getStampMetricsForA4Print(pageWidth, pageHeight) {
    const printScale = getA4PrintScaleForPage(pageWidth, pageHeight);
    const metricScale = printScale > 0 ? 1 / printScale : 1;
    return {
        printScale,
        fontSize: DEFAULT_FONT_SIZE * metricScale,
        marginRight: MARGIN_RIGHT * metricScale,
        marginTop: MARGIN_TOP * metricScale,
        outline: STAMP_OUTLINE * metricScale,
    };
}
async function ensureStampFont(fontSize) {
    const fonts = document.fonts;
    if (!fonts) {
        return;
    }
    await fonts.load(`700 ${fontSize}px "Noto Sans JP"`);
    await fonts.ready;
}
async function canvasToPngBytes(canvas) {
    const blob = await new Promise((resolve, reject) => {
        canvas.toBlob(result => {
            if (result)
                resolve(result);
            else
                reject(new Error('スタンプ画像を作成できませんでした。'));
        }, 'image/png');
    });
    return new Uint8Array(await blob.arrayBuffer());
}
async function createStampImage(stampText, fontSize, outline) {
    await ensureStampFont(fontSize);
    const scale = 3;
    const measureCanvas = document.createElement('canvas');
    const measureContext = measureCanvas.getContext('2d');
    if (!measureContext) {
        throw new Error('Canvasを初期化できませんでした。');
    }
    const font = `700 ${fontSize * scale}px "Noto Sans JP", sans-serif`;
    measureContext.font = font;
    const padding = Math.ceil((outline + 3) * scale);
    const measured = measureContext.measureText(stampText);
    const widthPx = Math.ceil(measured.width + padding * 2);
    const heightPx = Math.ceil(fontSize * 1.32 * scale + padding * 2);
    const canvas = document.createElement('canvas');
    canvas.width = widthPx;
    canvas.height = heightPx;
    const context = canvas.getContext('2d');
    if (!context) {
        throw new Error('Canvasを初期化できませんでした。');
    }
    context.font = font;
    context.textBaseline = 'top';
    context.lineJoin = 'round';
    context.lineWidth = Math.max(1, outline * 2 * scale);
    context.strokeStyle = '#ffffff';
    context.fillStyle = '#ff0000';
    context.strokeText(stampText, padding, padding);
    context.fillText(stampText, padding, padding);
    return {
        bytes: await canvasToPngBytes(canvas),
        width: widthPx / scale,
        height: heightPx / scale,
    };
}
async function ensureA4Pages(pdfBytes) {
    const srcDoc = await PDFLib.PDFDocument.load(pdfBytes);
    const srcPages = srcDoc.getPages();
    const needsResize = srcPages.some((page) => {
        const { width, height } = page.getSize();
        return !isA4PageSize(width, height);
    });
    if (!needsResize) {
        return pdfBytes;
    }
    const newDoc = await PDFLib.PDFDocument.create();
    for (let index = 0; index < srcPages.length; index++) {
        const srcPage = srcPages[index];
        const { width, height } = srcPage.getSize();
        if (!isA4PageSize(width, height)) {
            const placement = getA4Placement(width, height);
            const newPage = newDoc.addPage([placement.pageW, placement.pageH]);
            if (pageHasContents(srcPage)) {
                const embedded = await newDoc.embedPage(srcPage);
                newPage.drawPage(embedded, placement);
            }
        }
        else {
            const [copiedPage] = await newDoc.copyPages(srcDoc, [index]);
            newDoc.addPage(copiedPage);
        }
    }
    return await newDoc.save();
}
async function convertImageToPdf(file) {
    const imageBytes = new Uint8Array(await file.arrayBuffer());
    const pdfDoc = await PDFLib.PDFDocument.create();
    const image = getExtname(file.name) === '.png'
        ? await pdfDoc.embedPng(imageBytes)
        : await pdfDoc.embedJpg(imageBytes);
    const [pageW, pageH] = getA4PageSizeForPage(image.width, image.height);
    const page = pdfDoc.addPage([pageW, pageH]);
    const maxW = pageW - IMAGE_MARGIN * 2;
    const maxH = pageH - IMAGE_MARGIN * 2;
    const scale = Math.min(maxW / image.width, maxH / image.height, 1);
    const drawW = image.width * scale;
    const drawH = image.height * scale;
    page.drawImage(image, {
        x: (pageW - drawW) / 2,
        y: (pageH - drawH) / 2,
        width: drawW,
        height: drawH,
    });
    return await pdfDoc.save();
}
async function stampPdfBytes(inputBytes, evidenceNumber, options) {
    const normalizedBytes = await ensureA4Pages(inputBytes);
    const pdfDoc = await PDFLib.PDFDocument.load(normalizedBytes);
    const pages = pdfDoc.getPages();
    const pagesToStamp = options.allPages ? pages : pages.slice(0, 1);
    for (const page of pagesToStamp) {
        const { width, height } = page.getSize();
        const metrics = getStampMetricsForA4Print(width, height);
        const stamp = await createStampImage(`${evidenceNumber}${STAMP_SUFFIX}`, metrics.fontSize, metrics.outline);
        const stampImage = await pdfDoc.embedPng(stamp.bytes);
        page.drawImage(stampImage, {
            x: width - stamp.width - metrics.marginRight,
            y: height - stamp.height - metrics.marginTop,
            width: stamp.width,
            height: stamp.height,
        });
    }
    return {
        bytes: await pdfDoc.save(),
        pageCount: pages.length,
    };
}
async function processFile(selectedFile, options) {
    if (!selectedFile.evidenceNumber || !selectedFile.supported) {
        return null;
    }
    appendLog(`処理中: ${selectedFile.file.name}`);
    const inputBytes = isImageFile(selectedFile.file)
        ? await convertImageToPdf(selectedFile.file)
        : new Uint8Array(await selectedFile.file.arrayBuffer());
    const result = await stampPdfBytes(inputBytes, selectedFile.evidenceNumber, options);
    appendLog(`完了: ${selectedFile.evidenceNumber}${STAMP_SUFFIX}`);
    return {
        filename: `${stripExtname(selectedFile.file.name)}.pdf`,
        evidenceNumber: selectedFile.evidenceNumber,
        bytes: result.bytes,
        pageCount: result.pageCount,
    };
}
async function mergeStampedPdfs(stampedPdfs, insertBlankPages) {
    const mergedDoc = await PDFLib.PDFDocument.create();
    let totalPages = 0;
    let blankPages = 0;
    for (let index = 0; index < stampedPdfs.length; index++) {
        const sourceDoc = await PDFLib.PDFDocument.load(stampedPdfs[index].bytes);
        const copiedPages = await mergedDoc.copyPages(sourceDoc, sourceDoc.getPageIndices());
        for (const page of copiedPages) {
            mergedDoc.addPage(page);
            totalPages++;
        }
        if (insertBlankPages && copiedPages.length % 2 !== 0 && index < stampedPdfs.length - 1) {
            const lastPage = copiedPages[copiedPages.length - 1];
            const { width, height } = lastPage.getSize();
            mergedDoc.addPage([width, height]);
            totalPages++;
            blankPages++;
        }
    }
    return {
        bytes: await mergedDoc.save(),
        totalPages,
        blankPages,
    };
}
function makeDownloadBlob(bytes, mimeType) {
    const arrayBuffer = bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength);
    return new Blob([arrayBuffer], { type: mimeType });
}
function downloadBytes(filename, bytes, mimeType) {
    const url = URL.createObjectURL(makeDownloadBlob(bytes, mimeType));
    const link = document.createElement('a');
    link.href = url;
    link.download = filename;
    document.body.appendChild(link);
    link.click();
    link.remove();
    URL.revokeObjectURL(url);
}
function buildOutputZip(stampedPdfs, mergedBytes) {
    const entries = stampedPdfs.map(pdf => ({
        path: `stamped/${pdf.filename}`,
        data: pdf.bytes,
    }));
    if (mergedBytes) {
        entries.push({
            path: 'stamped/_結合_号証一式.pdf',
            data: mergedBytes,
        });
    }
    return (0, zip_1.buildStoredZip)(entries);
}
function updateSelectedFiles(files) {
    selectedFiles = files
        .map(file => ({
        file,
        evidenceNumber: extractEvidenceNumber(file.name),
        supported: isSupportedFile(file),
        sortKey: naturalSortKey(file.name),
    }))
        .sort((a, b) => a.sortKey[0] - b.sortKey[0] || a.sortKey[1] - b.sortKey[1] || a.sortKey[2] - b.sortKey[2] || a.file.name.localeCompare(b.file.name, 'ja'));
    const supported = selectedFiles.filter(item => item.supported);
    const stampable = selectedFiles.filter(item => item.supported && item.evidenceNumber);
    const skipped = selectedFiles.length - stampable.length;
    stampSummary.textContent = selectedFiles.length === 0
        ? 'PDF、JPG、PNGを選択してください。'
        : `${selectedFiles.length}件を選択中。スタンプ対象 ${stampable.length}件、除外 ${skipped}件。`;
    stampButton.disabled = stampable.length === 0;
    setStatus(stampable.length === 0 ? '対象ファイルなし' : '作成できます');
    stampLog.value = '';
    for (const item of selectedFiles) {
        if (!item.supported) {
            appendLog(`除外: ${item.file.name}（PDF/JPG/PNGではありません）`);
        }
        else if (!item.evidenceNumber) {
            appendLog(`除外: ${item.file.name}（ファイル名の先頭に号証番号がありません）`);
        }
        else {
            appendLog(`対象: ${item.evidenceNumber}${STAMP_SUFFIX} ← ${item.file.name}`);
        }
    }
    if (supported.length === 0 && selectedFiles.length > 0) {
        setStatus('対象ファイルなし');
    }
}
function getOptions() {
    return {
        allPages: allPagesCheckbox.checked,
        insertBlankPages: !noBlankPagesCheckbox.checked,
    };
}
async function runStamp() {
    if (!window.PDFLib) {
        setStatus('PDF処理ライブラリを読み込めませんでした。ネットワークを確認してください。');
        return;
    }
    const targets = selectedFiles.filter(item => item.supported && item.evidenceNumber);
    if (targets.length === 0) {
        return;
    }
    stampButton.disabled = true;
    setStatus('作成中...');
    setProgress(0, targets.length + (targets.length > 1 ? 1 : 0));
    stampLog.value = '';
    try {
        const options = getOptions();
        const stampedPdfs = [];
        for (let index = 0; index < targets.length; index++) {
            const target = targets[index];
            const stampedPdf = await processFile(target, options);
            if (stampedPdf) {
                stampedPdfs.push(stampedPdf);
            }
            setProgress(index + 1, targets.length + (targets.length > 1 ? 1 : 0));
        }
        if (stampedPdfs.length === 1) {
            downloadBytes(stampedPdfs[0].filename, stampedPdfs[0].bytes, 'application/pdf');
            setProgress(1, 1);
            setStatus('作成しました。');
            return;
        }
        const merged = await mergeStampedPdfs(stampedPdfs, options.insertBlankPages);
        const zipBytes = buildOutputZip(stampedPdfs, merged.bytes);
        downloadBytes('stamped_号証一式.zip', zipBytes, 'application/zip');
        setProgress(targets.length + 1, targets.length + 1);
        appendLog(`結合PDF: ${merged.totalPages}ページ（空白ページ ${merged.blankPages}ページ）`);
        setStatus(`作成しました。${stampedPdfs.length}件をZIPにまとめました。`);
    }
    catch (err) {
        console.error(err);
        appendLog(`エラー: ${err instanceof Error ? err.message : String(err)}`);
        setStatus('作成に失敗しました。ファイルを確認してください。');
    }
    finally {
        stampButton.disabled = selectedFiles.filter(item => item.supported && item.evidenceNumber).length === 0;
    }
}
function filesFromInput(fileList) {
    return Array.from(fileList || []);
}
chooseFilesButton.addEventListener('click', () => fileInput.click());
stampButton.addEventListener('click', runStamp);
fileInput.addEventListener('change', () => updateSelectedFiles(filesFromInput(fileInput.files)));
dropZone.addEventListener('click', () => fileInput.click());
dropZone.addEventListener('dragover', event => {
    event.preventDefault();
    dropZone.classList.add('drag-over');
});
dropZone.addEventListener('dragleave', () => dropZone.classList.remove('drag-over'));
dropZone.addEventListener('drop', event => {
    event.preventDefault();
    dropZone.classList.remove('drag-over');
    updateSelectedFiles(filesFromInput(event.dataTransfer?.files || null));
});
stampButton.disabled = true;
setProgress(0, 1);
updateSelectedFiles([]);

}
  };
  var cache = {};
  function resolve(from, request) {
    if (request.charAt(0) !== '.') return request;
    var parts = from.split('/');
    parts.pop();
    var raw = parts.concat(request.split('/'));
    var out = [];
    for (var i = 0; i < raw.length; i++) {
      var part = raw[i];
      if (!part || part === '.') continue;
      if (part === '..') out.pop();
      else out.push(part);
    }
    return out.join('/').replace(/\.(js|ts)$/, '');
  }
  function load(id) {
    if (cache[id]) return cache[id].exports;
    if (!modules[id]) throw new Error('Module not found: ' + id);
    var module = { exports: {} };
    cache[id] = module;
    modules[id](function (request) { return load(resolve(id, request)); }, module, module.exports);
    return module.exports;
  }
  load("src/web/stamp");
}());
